#!/usr/bin/env python3
"""
Giselle -> Vibexe Rename Script
================================
Safe, ordered rename of all "giselle" occurrences in the vibexe codebase.

Usage:
  python rename-giselle.py              # Dry-run (default) - shows what would change
  python rename-giselle.py --execute    # Actually perform the rename
  python rename-giselle.py --stats      # Show count summary only

Reference: .claude/projects/.../memory/giselle-rename-operation.md
"""

import os
import sys
import json
from pathlib import Path
from collections import defaultdict

# ============================================================================
# CONFIGURATION
# ============================================================================

PROJECT_ROOT = Path(__file__).parent.resolve()

# Execution mode
EXECUTE = "--execute" in sys.argv
STATS_ONLY = "--stats" in sys.argv

# Directories to skip entirely (matched against directory name, not path)
SKIP_DIRS = {
    "node_modules", ".next", ".git", ".turbo", "dist", ".cache",
    ".pnpm", ".playwright-mcp", "__pycache__", ".vercel",
    ".continuity",  # historical snapshots, not active code
}

# Files to skip entirely
SKIP_FILES = {
    "pnpm-lock.yaml",       # regenerated by pnpm install
    "rename-giselle.py",    # this script
}

# Binary extensions to skip (can't do text replacement)
BINARY_EXTENSIONS = {
    ".png", ".jpg", ".jpeg", ".gif", ".ico", ".webp", ".avif",
    ".woff", ".woff2", ".ttf", ".eot", ".otf",
    ".mp4", ".webm", ".mp3", ".ogg", ".wav",
    ".zip", ".tar", ".gz", ".br", ".bz2", ".zst",
    ".wasm", ".node", ".dll", ".exe", ".so", ".dylib",
    ".pdf", ".lock", ".map",
    ".pyc", ".pyo", ".class",
}

# ============================================================================
# REPLACEMENT MAPPINGS (ORDER MATTERS — longest/most specific first)
# ============================================================================

CONTENT_REPLACEMENTS = [
    # --- GitHub full URL (avoid matching npm scope @giselles-ai/) ---
    ("github.com/giselles-ai/giselle", "github.com/Newpixel-net/vibexe"),

    # --- Subdomain patterns ---
    ("studio.giselles.ai", "studio.vibexe.ai"),
    ("ui.giselles.ai", "ui.vibexe.ai"),
    ("docs.giselles.ai", "docs.vibexe.ai"),

    # --- NPM scopes (with trailing slash for precision) ---
    ("@giselles-ai/", "@vibexe-ai/"),
    ("@giselle-internal/", "@vibexe-internal/"),

    # --- Kebab-case compound names ---
    ("giselles-ai", "vibexe-ai"),
    ("giselle-internal", "vibexe-internal"),
    ("giselle-project", "vibexe-project"),

    # --- Domain without subdomain ---
    ("giselles.ai", "vibexe.ai"),

    # --- Env var prefix (all caps + underscore) ---
    ("GISELLE_", "VIBEXE_"),

    # --- Remaining all caps ---
    ("GISELLE", "VIBEXE"),

    # --- Plural forms ---
    ("Giselles", "Vibexes"),
    ("giselles", "vibexes"),

    # --- Singular forms (LAST — catch-all) ---
    ("Giselle", "Vibexe"),
    ("giselle", "vibexe"),
]

# Directories to rename (relative to project root)
# Checked in order; only renamed if they exist
DIR_RENAMES = [
    ("apps/studio.giselles.ai", "apps/studio.vibexe.ai"),
    ("apps/ui.giselles.ai", "apps/ui.vibexe.ai"),
    ("packages/giselle", "packages/vibexe"),
]

# ============================================================================
# UTILITIES
# ============================================================================

def should_skip_dir(name):
    """Check if a directory should be skipped entirely."""
    return name in SKIP_DIRS


def should_skip_file(path):
    """Check if a file should be skipped."""
    if path.name in SKIP_FILES:
        return True
    if path.suffix.lower() in BINARY_EXTENSIONS:
        return True
    return False


def is_text_file(path):
    """Quick check if file is likely text (not binary)."""
    try:
        with open(path, "rb") as f:
            chunk = f.read(8192)
            if b"\x00" in chunk:  # null bytes = binary
                return False
        return True
    except (OSError, PermissionError):
        return False


def apply_replacements(text):
    """Apply all replacement rules in order. Returns (new_text, count)."""
    total_count = 0
    for old, new in CONTENT_REPLACEMENTS:
        count = text.count(old)
        if count > 0:
            text = text.replace(old, new)
            total_count += count
    return text, total_count


def apply_name_replacements(name):
    """Apply replacements to a filename or directory name."""
    for old, new in CONTENT_REPLACEMENTS:
        name = name.replace(old, new)
    return name


def walk_files(root):
    """Walk project tree, respecting skip rules. Yields Path objects."""
    for dirpath, dirnames, filenames in os.walk(root):
        # Filter out skip dirs (modifying dirnames in-place prevents descent)
        dirnames[:] = [d for d in dirnames if not should_skip_dir(d)]

        for fname in filenames:
            fpath = Path(dirpath) / fname
            if not should_skip_file(fpath):
                yield fpath


# ============================================================================
# PHASE A: Replace file contents
# ============================================================================

def phase_a_replace_contents():
    """Replace all giselle occurrences in file contents."""
    print("\n" + "=" * 70)
    print("PHASE A: Replace file contents")
    print("=" * 70)

    changed_files = {}       # path -> replacement count
    skipped_binary = 0
    skipped_error = 0
    total_replacements = 0

    for fpath in walk_files(PROJECT_ROOT):
        if not is_text_file(fpath):
            skipped_binary += 1
            continue

        try:
            with open(fpath, "r", encoding="utf-8", errors="replace") as f:
                content = f.read()
        except (OSError, PermissionError) as e:
            skipped_error += 1
            print(f"  SKIP (read error): {fpath} — {e}")
            continue

        new_content, count = apply_replacements(content)

        if count > 0:
            rel = fpath.relative_to(PROJECT_ROOT)
            changed_files[str(rel)] = count
            total_replacements += count

            if EXECUTE:
                try:
                    with open(fpath, "w", encoding="utf-8", newline="") as f:
                        f.write(new_content)
                except (OSError, PermissionError) as e:
                    print(f"  ERROR (write): {fpath} — {e}")

    # Report
    print(f"\n  Files with replacements: {len(changed_files)}")
    print(f"  Total replacements:     {total_replacements}")
    print(f"  Skipped (binary):       {skipped_binary}")
    print(f"  Skipped (error):        {skipped_error}")

    if not STATS_ONLY:
        # Show top 30 files by replacement count
        sorted_files = sorted(changed_files.items(), key=lambda x: -x[1])
        print(f"\n  Top files by replacement count:")
        for path, count in sorted_files[:30]:
            action = "CHANGED" if EXECUTE else "would change"
            print(f"    [{count:3d}] {action}: {path}")
        if len(sorted_files) > 30:
            print(f"    ... and {len(sorted_files) - 30} more files")

    return changed_files, total_replacements


# ============================================================================
# PHASE B: Rename files with "giselle" in name
# ============================================================================

def phase_b_rename_files():
    """Rename files that have 'giselle' (any case) in their filename."""
    print("\n" + "=" * 70)
    print("PHASE B: Rename files with 'giselle' in name")
    print("=" * 70)

    renames = []  # (old_path, new_path)

    for fpath in walk_files(PROJECT_ROOT):
        if "giselle" in fpath.name.lower():
            new_name = apply_name_replacements(fpath.name)
            if new_name != fpath.name:
                new_path = fpath.parent / new_name
                renames.append((fpath, new_path))

    print(f"\n  Files to rename: {len(renames)}")

    for old, new in renames:
        old_rel = old.relative_to(PROJECT_ROOT)
        new_rel = new.relative_to(PROJECT_ROOT)
        action = "RENAMED" if EXECUTE else "would rename"
        print(f"    {action}: {old_rel}")
        print(f"         -> {new_rel}")

        if EXECUTE:
            try:
                old.rename(new)
            except (OSError, PermissionError) as e:
                print(f"    ERROR: {e}")

    return renames


# ============================================================================
# PHASE C: Rename directories
# ============================================================================

def phase_c_rename_directories():
    """Rename directories containing 'giselle' in their name."""
    print("\n" + "=" * 70)
    print("PHASE C: Rename directories")
    print("=" * 70)

    renames_done = []

    # First: handle the known big directory renames
    for old_rel, new_rel in DIR_RENAMES:
        old_path = PROJECT_ROOT / old_rel
        new_path = PROJECT_ROOT / new_rel

        if old_path.exists():
            action = "RENAMED" if EXECUTE else "would rename"
            print(f"\n  {action}: {old_rel}/")
            print(f"       -> {new_rel}/")

            if EXECUTE:
                try:
                    old_path.rename(new_path)
                    renames_done.append((old_rel, new_rel))
                except (OSError, PermissionError) as e:
                    print(f"  ERROR: {e}")
            else:
                renames_done.append((old_rel, new_rel))
        else:
            print(f"\n  SKIP (not found): {old_rel}/")

    # Then: find any remaining directories with "giselle" in name
    # Walk bottom-up to rename deepest first
    remaining = []
    for dirpath, dirnames, _ in os.walk(PROJECT_ROOT, topdown=False):
        # Skip already-handled directories and skip-listed ones
        dp = Path(dirpath)
        if any(should_skip_dir(part) for part in dp.relative_to(PROJECT_ROOT).parts):
            continue

        for dname in dirnames:
            if should_skip_dir(dname):
                continue
            if "giselle" in dname.lower():
                full_old = dp / dname
                new_name = apply_name_replacements(dname)
                if new_name != dname:
                    full_new = dp / new_name
                    # Check it wasn't already renamed in DIR_RENAMES
                    rel_old = str(full_old.relative_to(PROJECT_ROOT)).replace("\\", "/")
                    already = any(rel_old == r[0] for r in DIR_RENAMES)
                    if not already:
                        remaining.append((full_old, full_new))

    if remaining:
        print(f"\n  Additional directory renames: {len(remaining)}")
        for old, new in remaining:
            old_rel = old.relative_to(PROJECT_ROOT)
            new_rel = new.relative_to(PROJECT_ROOT)
            action = "RENAMED" if EXECUTE else "would rename"
            print(f"    {action}: {old_rel}/")
            print(f"         -> {new_rel}/")

            if EXECUTE:
                try:
                    if old.exists():
                        old.rename(new)
                except (OSError, PermissionError) as e:
                    print(f"    ERROR: {e}")

    total = len(renames_done) + len(remaining)
    print(f"\n  Total directories renamed: {total}")
    return renames_done


# ============================================================================
# VERIFICATION
# ============================================================================

def verify_no_remaining():
    """Check for any remaining 'giselle' occurrences after rename."""
    print("\n" + "=" * 70)
    print("VERIFICATION: Checking for remaining 'giselle' occurrences")
    print("=" * 70)

    remaining_files = {}
    remaining_dirs = []
    remaining_filenames = []

    for fpath in walk_files(PROJECT_ROOT):
        # Check filename
        if "giselle" in fpath.name.lower():
            remaining_filenames.append(str(fpath.relative_to(PROJECT_ROOT)))

        # Check content
        if not is_text_file(fpath):
            continue
        try:
            with open(fpath, "r", encoding="utf-8", errors="replace") as f:
                content = f.read()
            lower = content.lower()
            count = lower.count("giselle")
            if count > 0:
                rel = str(fpath.relative_to(PROJECT_ROOT))
                remaining_files[rel] = count
        except (OSError, PermissionError):
            pass

    # Check directory names
    for dirpath, dirnames, _ in os.walk(PROJECT_ROOT):
        dirnames[:] = [d for d in dirnames if not should_skip_dir(d)]
        for d in dirnames:
            if "giselle" in d.lower():
                rel = str((Path(dirpath) / d).relative_to(PROJECT_ROOT))
                remaining_dirs.append(rel)

    if remaining_files or remaining_dirs or remaining_filenames:
        print(f"\n  WARNING: Found remaining occurrences!")
        if remaining_files:
            print(f"\n  Files with 'giselle' in content: {len(remaining_files)}")
            for path, count in sorted(remaining_files.items(), key=lambda x: -x[1])[:20]:
                print(f"    [{count:3d}] {path}")
            if len(remaining_files) > 20:
                print(f"    ... and {len(remaining_files) - 20} more")
        if remaining_filenames:
            print(f"\n  Files with 'giselle' in filename: {len(remaining_filenames)}")
            for f in remaining_filenames[:10]:
                print(f"    {f}")
        if remaining_dirs:
            print(f"\n  Dirs with 'giselle' in name: {len(remaining_dirs)}")
            for d in remaining_dirs[:10]:
                print(f"    {d}/")
    else:
        print("\n  ALL CLEAR — no remaining 'giselle' occurrences found!")

    return len(remaining_files) + len(remaining_dirs) + len(remaining_filenames)


# ============================================================================
# MAIN
# ============================================================================

def main():
    mode = "EXECUTE" if EXECUTE else "DRY-RUN"
    print("=" * 70)
    print(f"  GISELLE -> VIBEXE RENAME SCRIPT  [{mode} MODE]")
    print("=" * 70)
    print(f"  Project root: {PROJECT_ROOT}")
    print(f"  Mode: {'EXECUTE — files WILL be modified!' if EXECUTE else 'Dry-run — no files will be changed'}")
    print()

    if EXECUTE:
        print("  *** WARNING: This will modify files! ***")
        print("  Make sure you are on the 'rename/vibexe' branch.")
        print("  Make sure 'pre-rename-backup' tag exists.")
        print()
        confirm = input("  Type 'yes' to proceed: ").strip().lower()
        if confirm != "yes":
            print("  Aborted.")
            sys.exit(1)

    # Show replacement table
    print("\n  Replacement rules (applied in order):")
    print("  " + "-" * 66)
    for old, new in CONTENT_REPLACEMENTS:
        print(f"    {old:45s} -> {new}")
    print("  " + "-" * 66)

    # Phase A: Replace file contents
    changed_files, total_replacements = phase_a_replace_contents()

    # Phase B: Rename files
    file_renames = phase_b_rename_files()

    # Phase C: Rename directories
    dir_renames = phase_c_rename_directories()

    # Verification (only in execute mode)
    remaining = 0
    if EXECUTE:
        remaining = verify_no_remaining()

    # Final summary
    print("\n" + "=" * 70)
    print("  SUMMARY")
    print("=" * 70)
    print(f"  Mode:                   {mode}")
    print(f"  Files content-changed:  {len(changed_files)}")
    print(f"  Total replacements:     {total_replacements}")
    print(f"  Files renamed:          {len(file_renames)}")
    print(f"  Directories renamed:    {len(dir_renames)}")
    if EXECUTE:
        print(f"  Remaining occurrences:  {remaining}")

    if not EXECUTE:
        print("\n  To execute the rename, run:")
        print("    python rename-giselle.py --execute")
        print()
        print("  Before executing, make sure to:")
        print("    1. git checkout -b rename/vibexe")
        print("    2. Verify the dry-run output above looks correct")
        print()
        print("  After executing:")
        print("    1. pnpm install                              (regenerate lock file)")
        print("    2. pnpm build-sdk                            (rebuild all packages)")
        print("    3. pnpm --filter studio.vibexe.ai build      (test Next.js build)")
        print("    4. git add -A && git commit -m 'Rename giselle -> vibexe'")
        print("    5. git push origin rename/vibexe")
    else:
        print()
        print("  RENAME COMPLETE! Next steps:")
        print("    1. pnpm install                              (regenerate lock file)")
        print("    2. pnpm build-sdk                            (rebuild all packages)")
        print("    3. pnpm --filter studio.vibexe.ai build      (test Next.js build)")
        print("    4. git add -A && git commit -m 'Rename giselle -> vibexe'")
        print("    5. git push origin rename/vibexe")

    print()


if __name__ == "__main__":
    main()
