/**
 * Comprehensive catalog of all 615+ Activepieces integrations.
 * This is metadata only — actual piece packages are loaded on demand via dynamic import.
 *
 * Source: https://github.com/activepieces/activepieces/tree/main/packages/pieces/community
 */

import { type PieceType, getEnrichment } from "./piece-enrichment";

export type { PieceType } from "./piece-enrichment";

export interface PieceCatalogEntry {
	name: string;
	displayName: string;
	category: PieceCategory;
	authType: PieceAuthType;
	description: string;
	pieceType: PieceType;
	logoUrl?: string;
}

export type PieceCategory =
	| "AI & ML"
	| "Communication"
	| "CRM & Sales"
	| "Project Management"
	| "Email & Marketing"
	| "Google Workspace"
	| "Microsoft 365"
	| "Social Media"
	| "E-Commerce"
	| "Developer Tools"
	| "Productivity"
	| "Finance & Accounting"
	| "Cloud Storage"
	| "HR & Recruitment"
	| "Forms & Surveys"
	| "CMS & Website"
	| "Documents & Signatures"
	| "Automation & Utilities";

export type PieceAuthType =
	| "oauth2"
	| "api_key"
	| "secret_text"
	| "basic"
	| "custom"
	| "none";

function p(
	name: string,
	displayName: string,
	category: PieceCategory,
	authType: PieceAuthType = "api_key",
): PieceCatalogEntry {
	const enrichment = getEnrichment(name, category);
	return {
		name,
		displayName,
		category,
		authType,
		description: enrichment.description ?? `${category} integration`,
		pieceType: enrichment.pieceType ?? "regular",
		logoUrl: enrichment.logoUrl,
	};
}

/**
 * Full catalog of Activepieces integrations organized by category.
 */
export const PIECE_CATALOG: PieceCatalogEntry[] = [
	// ─── AI & ML ───────────────────────────────────────────
	p("openai", "OpenAI", "AI & ML", "api_key"),
	p("claude", "Claude (Anthropic)", "AI & ML", "api_key"),
	p("google-gemini", "Google Gemini", "AI & ML", "api_key"),
	p("azure-openai", "Azure OpenAI", "AI & ML", "custom"),
	p("deepseek", "DeepSeek", "AI & ML", "api_key"),
	p("groq", "Groq", "AI & ML", "api_key"),
	p("grok-xai", "Grok (xAI)", "AI & ML", "api_key"),
	p("mistral-ai", "Mistral AI", "AI & ML", "api_key"),
	p("hugging-face", "Hugging Face", "AI & ML", "api_key"),
	p("hume-ai", "Hume AI", "AI & ML", "api_key"),
	p("perplexity-ai", "Perplexity AI", "AI & ML", "api_key"),
	p("open-router", "OpenRouter", "AI & ML", "api_key"),
	p("stability-ai", "Stability AI", "AI & ML", "custom"),
	p("stable-diffusion-webui", "Stable Diffusion WebUI", "AI & ML", "custom"),
	p("elevenlabs", "ElevenLabs", "AI & ML", "custom"),
	p("deepgram", "Deepgram", "AI & ML", "api_key"),
	p("assemblyai", "AssemblyAI", "AI & ML", "api_key"),
	p("gladia", "Gladia", "AI & ML", "api_key"),
	p("eden-ai", "Eden AI", "AI & ML", "api_key"),
	p("clarifai", "Clarifai", "AI & ML", "api_key"),
	p("flowise", "Flowise", "AI & ML", "custom"),
	p("afforai", "Afforai", "AI & ML", "api_key"),
	p("aidbase", "Aidbase", "AI & ML", "api_key"),
	p("aianswer", "AI Answer", "AI & ML", "api_key"),
	p("ai", "AI", "AI & ML", "none"),
	p("alt-text-ai", "Alt Text AI", "AI & ML", "api_key"),
	p("alttextify", "Alttextify", "AI & ML", "api_key"),
	p("copy-ai", "Copy.ai", "AI & ML", "api_key"),
	p("textcortex-ai", "TextCortex AI", "AI & ML", "api_key"),
	p("detecting-ai", "Detecting AI", "AI & ML", "api_key"),
	p("gptzero-detect-ai", "GPTZero", "AI & ML", "api_key"),
	p("straico", "Straico", "AI & ML", "api_key"),
	p("contextual-ai", "Contextual AI", "AI & ML", "custom"),
	p("mind-studio", "Mind Studio", "AI & ML", "api_key"),
	p("devin", "Devin", "AI & ML", "api_key"),
	p("cursor", "Cursor", "AI & ML", "api_key"),
	p("griptape", "Griptape", "AI & ML", "api_key"),
	p("letta", "Letta", "AI & ML", "custom"),
	p("mcp", "MCP", "AI & ML", "none"),
	p("localai", "LocalAI", "AI & ML", "custom"),
	p("runway", "Runway", "AI & ML", "api_key"),
	p("comfyicu", "ComfyICU", "AI & ML", "api_key"),
	p("synthesia", "Synthesia", "AI & ML", "api_key"),
	p("heygen", "HeyGen", "AI & ML", "api_key"),
	p("jogg-ai", "Jogg AI", "AI & ML", "api_key"),
	p("vidnoz", "Vidnoz", "AI & ML", "api_key"),
	p("camb-ai", "Camb AI", "AI & ML", "api_key"),
	p("murf-api", "Murf API", "AI & ML", "api_key"),
	p("bolna", "Bolna", "AI & ML", "api_key"),
	p("agentx", "AgentX", "AI & ML", "api_key"),
	p("air-ops", "Air Ops", "AI & ML", "api_key"),
	p("airparser", "Airparser", "AI & ML", "api_key"),
	p("airtop", "Airtop", "AI & ML", "api_key"),
	p("alai", "Alai", "AI & ML", "custom"),
	p("easy-peasy-ai", "Easy Peasy AI", "AI & ML", "api_key"),
	p("echowin", "Echowin", "AI & ML", "api_key"),
	p("exa", "Exa", "AI & ML", "api_key"),
	p("extracta-ai", "Extracta AI", "AI & ML", "api_key"),
	p("firecrawl", "Firecrawl", "AI & ML", "api_key"),
	p("fireflies-ai", "Fireflies AI", "AI & ML", "api_key"),
	p("insighto-ai", "Insighto AI", "AI & ML", "api_key"),
	p("jina-ai", "Jina AI", "AI & ML", "api_key"),
	p("kallabot-ai", "Kallabot AI", "AI & ML", "api_key"),
	p("leap-ai", "Leap AI", "AI & ML", "api_key"),
	p("llmrails", "LLM Rails", "AI & ML", "api_key"),
	p("magical-api", "Magical API", "AI & ML", "api_key"),
	p("magicslides", "MagicSlides", "AI & ML", "custom"),
	p("meetgeek-ai", "MeetGeek AI", "AI & ML", "api_key"),
	p("mindee", "Mindee", "AI & ML", "api_key"),
	p("moveo-ai", "Moveo AI", "AI & ML", "api_key"),
	p("openmic-ai", "OpenMic AI", "AI & ML", "api_key"),
	p("personal-ai", "Personal AI", "AI & ML", "api_key"),
	p("phantombuster", "PhantomBuster", "AI & ML", "api_key"),
	p("photoroom", "PhotoRoom", "AI & ML", "custom"),
	p("predis-ai", "Predis AI", "AI & ML", "api_key"),
	p("prompthub", "PromptHub", "AI & ML", "api_key"),
	p("promptmate", "PromptMate", "AI & ML", "api_key"),
	p("raia-ai", "Raia AI", "AI & ML", "api_key"),
	p("rapidtext-ai", "RapidText AI", "AI & ML", "api_key"),
	p("recall-ai", "Recall AI", "AI & ML", "custom"),
	p("retell-ai", "Retell AI", "AI & ML", "custom"),
	p("retune", "Retune", "AI & ML", "custom"),
	p("returning-ai", "Returning AI", "AI & ML", "api_key"),
	p("roe-ai", "Roe AI", "AI & ML", "custom"),
	p("runware", "Runware", "AI & ML", "api_key"),
	p("scenario", "Scenario", "AI & ML", "basic"),
	p("scrapegrapghai", "ScrapeGraph AI", "AI & ML", "api_key"),
	p("sitespeakai", "SiteSpeakAI", "AI & ML", "api_key"),
	p("skyvern", "Skyvern", "AI & ML", "api_key"),
	p("slidespeak", "SlidespEAK", "AI & ML", "api_key"),
	p("tavily", "Tavily", "AI & ML", "api_key"),
	p("vlm-run", "VLM Run", "AI & ML", "api_key"),
	p("webscraping-ai", "WebScraping AI", "AI & ML", "api_key"),
	p("writesonic-bulk", "Writesonic", "AI & ML", "api_key"),
	p("deepl", "DeepL", "AI & ML", "custom"),
	p("denser-ai", "Denser AI", "AI & ML", "custom"),
	p("docsbot", "DocsBot", "AI & ML", "api_key"),
	p("customgpt", "CustomGPT", "AI & ML", "api_key"),
	p("agent", "Agent", "AI & ML", "none"),
	p("dumpling-ai", "Dumpling AI", "AI & ML", "api_key"),
	p("dust", "Dust", "AI & ML", "custom"),

	// ─── Communication ─────────────────────────────────────
	p("slack", "Slack", "Communication", "oauth2"),
	p("discord", "Discord", "Communication", "api_key"),
	p("telegram-bot", "Telegram Bot", "Communication", "api_key"),
	p("microsoft-teams", "Microsoft Teams", "Communication", "oauth2"),
	p("mattermost", "Mattermost", "Communication", "custom"),
	p("whatsapp", "WhatsApp", "Communication", "custom"),
	p("line", "LINE", "Communication", "api_key"),
	p("googlechat", "Google Chat", "Communication", "oauth2"),
	p("intercom", "Intercom", "Communication", "oauth2"),
	p("crisp", "Crisp", "Communication", "custom"),
	p("front", "Front", "Communication", "api_key"),
	p("missive", "Missive", "Communication", "api_key"),
	p("manychat", "ManyChat", "Communication", "api_key"),
	p("respond-io", "Respond.io", "Communication", "custom"),
	p("freshdesk", "Freshdesk", "Communication", "custom"),
	p("zendesk", "Zendesk", "Communication", "custom"),
	p("help-scout", "Help Scout", "Communication", "oauth2"),
	p("chatbase", "Chatbase", "Communication", "api_key"),
	p("chatfly", "Chatfly", "Communication", "api_key"),
	p("chatling", "Chatling", "Communication", "api_key"),
	p("chatnode", "Chatnode", "Communication", "api_key"),
	p("chat-data", "Chat Data", "Communication", "api_key"),
	p("chat-aid", "Chat Aid", "Communication", "api_key"),
	p("chatsistant", "Chatsistant", "Communication", "api_key"),
	p("wonderchat", "Wonderchat", "Communication", "api_key"),
	p("pylon", "Pylon", "Communication", "api_key"),
	p("bonjoro", "Bonjoro", "Communication", "custom"),
	p("heymarket-sms", "Heymarket SMS", "Communication", "api_key"),
	p("clicksend", "ClickSend", "Communication", "basic"),
	p("messagebird", "MessageBird", "Communication", "custom"),
	p("twilio", "Twilio", "Communication", "basic"),
	p("octopush-sms", "Octopush SMS", "Communication", "custom"),
	p("smsmode", "SMSMode", "Communication", "api_key"),
	p("instasent", "InstaSent", "Communication", "custom"),
	p("seven", "Seven", "Communication", "api_key"),
	p("open-phone", "OpenPhone", "Communication", "api_key"),
	p("voipstudio", "VoIPStudio", "Communication", "api_key"),
	p("krisp-call", "Krisp Call", "Communication", "custom"),
	p("rounded-studio", "Call Rounded", "Communication", "api_key"),
	p("aircall", "Aircall", "Communication", "basic"),
	p("autocalls", "AutoCalls", "Communication", "api_key"),
	p("gotify", "Gotify", "Communication", "custom"),
	p("ntfy", "Ntfy", "Communication", "custom"),
	p("pushbullet", "Pushbullet", "Communication", "api_key"),
	p("pushover", "Pushover", "Communication", "custom"),
	p("matrix", "Matrix", "Communication", "custom"),
	p("discourse", "Discourse", "Communication", "custom"),

	// ─── CRM & Sales ───────────────────────────────────────
	p("hubspot", "HubSpot", "CRM & Sales", "oauth2"),
	p("salesforce", "Salesforce", "CRM & Sales", "oauth2"),
	p("pipedrive", "Pipedrive", "CRM & Sales", "oauth2"),
	p("close", "Close", "CRM & Sales", "api_key"),
	p("copper", "Copper", "CRM & Sales", "custom"),
	p("freshsales", "Freshsales", "CRM & Sales", "basic"),
	p("attio", "Attio", "CRM & Sales", "api_key"),
	p("zoho-crm", "Zoho CRM", "CRM & Sales", "oauth2"),
	p("bigin-by-zoho", "Bigin by Zoho", "CRM & Sales", "oauth2"),
	p("activecampaign", "ActiveCampaign", "CRM & Sales", "custom"),
	p("kommo", "Kommo", "CRM & Sales", "custom"),
	p("insightly", "Insightly", "CRM & Sales", "api_key"),
	p("capsule-crm", "Capsule CRM", "CRM & Sales", "oauth2"),
	p("folk", "Folk", "CRM & Sales", "api_key"),
	p("lead-connector", "Lead Connector", "CRM & Sales", "oauth2"),
	p("moxie-crm", "Moxie CRM", "CRM & Sales", "custom"),
	p("wealthbox", "Wealthbox", "CRM & Sales", "api_key"),
	p("microsoft-dynamics-crm", "Microsoft Dynamics CRM", "CRM & Sales", "oauth2"),
	p("apollo", "Apollo", "CRM & Sales", "api_key"),
	p("ashby", "Ashby", "CRM & Sales", "custom"),
	p("lever", "Lever", "CRM & Sales", "custom"),
	p("hunter", "Hunter", "CRM & Sales", "api_key"),
	p("clearout", "Clearout", "CRM & Sales", "custom"),
	p("lusha", "Lusha", "CRM & Sales", "api_key"),
	p("predict-leads", "Predict Leads", "CRM & Sales", "custom"),
	p("vtiger", "Vtiger", "CRM & Sales", "custom"),
	p("lofty", "Lofty", "CRM & Sales", "api_key"),
	p("fireberry", "Fireberry", "CRM & Sales", "api_key"),
	p("blackbaud", "Blackbaud", "CRM & Sales", "oauth2"),
	p("bloomerang", "Bloomerang", "CRM & Sales", "api_key"),
	p("linka", "Linka", "CRM & Sales", "custom"),
	p("qwilr", "Qwilr", "CRM & Sales", "api_key"),
	p("salsa", "Salsa", "CRM & Sales", "api_key"),

	// ─── Project Management ────────────────────────────────
	p("asana", "Asana", "Project Management", "oauth2"),
	p("clickup", "ClickUp", "Project Management", "oauth2"),
	p("trello", "Trello", "Project Management", "basic"),
	p("monday", "Monday.com", "Project Management", "api_key"),
	p("linear", "Linear", "Project Management", "api_key"),
	p("notion", "Notion", "Project Management", "oauth2"),
	p("jira-cloud", "Jira Cloud", "Project Management", "custom"),
	p("todoist", "Todoist", "Project Management", "oauth2"),
	p("baserow", "Baserow", "Project Management", "custom"),
	p("airtable", "Airtable", "Project Management", "api_key"),
	p("smartsheet", "Smartsheet", "Project Management", "api_key"),
	p("smartsuite", "SmartSuite", "Project Management", "custom"),
	p("coda", "Coda", "Project Management", "api_key"),
	p("wrike", "Wrike", "Project Management", "oauth2"),
	p("taskade", "Taskade", "Project Management", "api_key"),
	p("meistertask", "MeisterTask", "Project Management", "oauth2"),
	p("ticktick", "TickTick", "Project Management", "oauth2"),
	p("nocodb", "NocoDB", "Project Management", "custom"),
	p("retable", "Retable", "Project Management", "api_key"),
	p("apitable", "APITable", "Project Management", "custom"),
	p("bika", "Bika", "Project Management", "custom"),
	p("grist", "Grist", "Project Management", "custom"),
	p("quickbase", "QuickBase", "Project Management", "custom"),
	p("podio", "Podio", "Project Management", "oauth2"),
	p("flowlu", "Flowlu", "Project Management", "custom"),
	p("frame", "Frame", "Project Management", "api_key"),
	p("productboard", "Productboard", "Project Management", "api_key"),
	p("teamwork", "Teamwork", "Project Management", "custom"),
	p("teamleader", "Teamleader", "Project Management", "oauth2"),

	// ─── Email & Marketing ─────────────────────────────────
	p("gmail", "Gmail", "Email & Marketing", "oauth2"),
	p("mailchimp", "Mailchimp", "Email & Marketing", "oauth2"),
	p("sendinblue", "Brevo (Sendinblue)", "Email & Marketing", "api_key"),
	p("sendgrid", "SendGrid", "Email & Marketing", "api_key"),
	p("mailjet", "Mailjet", "Email & Marketing", "basic"),
	p("mailer-lite", "MailerLite", "Email & Marketing", "api_key"),
	p("convertkit", "ConvertKit", "Email & Marketing", "api_key"),
	p("constant-contact", "Constant Contact", "Email & Marketing", "oauth2"),
	p("campaign-monitor", "Campaign Monitor", "Email & Marketing", "api_key"),
	p("customer-io", "Customer.io", "Email & Marketing", "custom"),
	p("drip", "Drip", "Email & Marketing", "api_key"),
	p("lemlist", "Lemlist", "Email & Marketing", "api_key"),
	p("beehiiv", "Beehiiv", "Email & Marketing", "api_key"),
	p("vbout", "VBOUT", "Email & Marketing", "api_key"),
	p("emailoctopus", "EmailOctopus", "Email & Marketing", "api_key"),
	p("maileroo", "Maileroo", "Email & Marketing", "custom"),
	p("instantly-ai", "Instantly", "Email & Marketing", "api_key"),
	p("reachinbox", "ReachInbox", "Email & Marketing", "api_key"),
	p("sendpulse", "SendPulse", "Email & Marketing", "custom"),
	p("amazon-ses", "Amazon SES", "Email & Marketing", "api_key"),
	p("smtp", "SMTP", "Email & Marketing", "custom"),
	p("sendfox", "SendFox", "Email & Marketing", "api_key"),
	p("smaily", "Smaily", "Email & Marketing", "custom"),
	p("nuelink", "Nuelink", "Email & Marketing", "api_key"),
	p("tarvent", "Tarvent", "Email & Marketing", "custom"),
	p("zoho-campaigns", "Zoho Campaigns", "Email & Marketing", "oauth2"),
	p("zoho-mail", "Zoho Mail", "Email & Marketing", "oauth2"),
	p("imap", "IMAP", "Email & Marketing", "custom"),
	p("resend", "Resend", "Email & Marketing", "api_key"),
	p("sender", "Sender", "Email & Marketing", "api_key"),
	p("sendy", "Sendy", "Email & Marketing", "custom"),
	p("acumbamail", "Acumbamail", "Email & Marketing", "api_key"),
	p("mailchain", "Mailchain", "Email & Marketing", "api_key"),
	p("mailercheck", "MailerCheck", "Email & Marketing", "api_key"),
	p("smoove", "Smoove", "Email & Marketing", "api_key"),
	p("woodpecker", "Woodpecker", "Email & Marketing", "api_key"),
	p("mautic", "Mautic", "Email & Marketing", "custom"),
	p("plausible", "Plausible", "Email & Marketing", "api_key"),

	// ─── Google Workspace ──────────────────────────────────
	p("google-sheets", "Google Sheets", "Google Workspace", "none"),
	p("google-drive", "Google Drive", "Google Workspace", "oauth2"),
	p("google-calendar", "Google Calendar", "Google Workspace", "oauth2"),
	p("google-contacts", "Google Contacts", "Google Workspace", "oauth2"),
	p("google-docs", "Google Docs", "Google Workspace", "oauth2"),
	p("google-forms", "Google Forms", "Google Workspace", "oauth2"),
	p("google-slides", "Google Slides", "Google Workspace", "oauth2"),
	p("google-tasks", "Google Tasks", "Google Workspace", "oauth2"),
	p("google-my-business", "Google My Business", "Google Workspace", "oauth2"),
	p("google-search", "Google Search", "Google Workspace", "custom"),
	p("google-search-console", "Google Search Console", "Google Workspace", "oauth2"),
	p("google-cloud-storage", "Google Cloud Storage", "Google Workspace", "oauth2"),

	// ─── Microsoft 365 ─────────────────────────────────────
	p("microsoft-excel-365", "Microsoft Excel 365", "Microsoft 365", "oauth2"),
	p("microsoft-onedrive", "Microsoft OneDrive", "Microsoft 365", "oauth2"),
	p("microsoft-onenote", "Microsoft OneNote", "Microsoft 365", "oauth2"),
	p("microsoft-outlook", "Microsoft Outlook", "Microsoft 365", "oauth2"),
	p("microsoft-outlook-calendar", "Outlook Calendar", "Microsoft 365", "oauth2"),
	p("microsoft-power-bi", "Microsoft Power BI", "Microsoft 365", "oauth2"),
	p("microsoft-sharepoint", "Microsoft SharePoint", "Microsoft 365", "oauth2"),
	p("microsoft-todo", "Microsoft To Do", "Microsoft 365", "oauth2"),
	p("microsoft-365-people", "Microsoft 365 People", "Microsoft 365", "oauth2"),
	p("microsoft-365-planner", "Microsoft 365 Planner", "Microsoft 365", "oauth2"),
	p("microsoft-dynamics-365-business-central", "Dynamics 365 BC", "Microsoft 365", "oauth2"),

	// ─── Social Media ──────────────────────────────────────
	p("twitter", "Twitter/X", "Social Media", "custom"),
	p("linkedin", "LinkedIn", "Social Media", "oauth2"),
	p("facebook-pages", "Facebook Pages", "Social Media", "oauth2"),
	p("facebook-leads", "Facebook Leads", "Social Media", "oauth2"),
	p("instagram-business", "Instagram Business", "Social Media", "oauth2"),
	p("bluesky", "Bluesky", "Social Media", "custom"),
	p("reddit", "Reddit", "Social Media", "oauth2"),
	p("mastodon", "Mastodon", "Social Media", "custom"),
	p("pinterest", "Pinterest", "Social Media", "oauth2"),
	p("youtube", "YouTube", "Social Media", "oauth2"),
	p("twitch", "Twitch", "Social Media", "oauth2"),
	p("spotify", "Spotify", "Social Media", "oauth2"),
	p("vimeo", "Vimeo", "Social Media", "oauth2"),
	p("hackernews", "Hacker News", "Social Media", "none"),
	p("rss", "RSS", "Social Media", "none"),

	// ─── E-Commerce ────────────────────────────────────────
	p("shopify", "Shopify", "E-Commerce", "custom"),
	p("woocommerce", "WooCommerce", "E-Commerce", "custom"),
	p("stripe", "Stripe", "E-Commerce", "api_key"),
	p("paypal", "PayPal", "E-Commerce", "custom"),
	p("square", "Square", "E-Commerce", "oauth2"),
	p("bigcommerce", "BigCommerce", "E-Commerce", "custom"),
	p("lemon-squeezy", "Lemon Squeezy", "E-Commerce", "api_key"),
	p("saleor", "Saleor", "E-Commerce", "custom"),
	p("vtex", "VTEX", "E-Commerce", "custom"),
	p("cartloom", "Cartloom", "E-Commerce", "custom"),
	p("cashfree-payments", "Cashfree", "E-Commerce", "custom"),
	p("razorpay", "Razorpay", "E-Commerce", "custom"),
	p("mollie", "Mollie", "E-Commerce", "api_key"),
	p("billplz", "Billplz", "E-Commerce", "api_key"),
	p("moonclerk", "MoonClerk", "E-Commerce", "api_key"),
	p("pinch-payments", "Pinch Payments", "E-Commerce", "custom"),
	p("quickzu", "Quickzu", "E-Commerce", "api_key"),
	p("paywhirl", "PayWhirl", "E-Commerce", "custom"),
	p("shippo", "Shippo", "E-Commerce", "api_key"),

	// ─── Developer Tools ───────────────────────────────────
	p("github", "GitHub", "Developer Tools", "oauth2"),
	p("gitlab", "GitLab", "Developer Tools", "oauth2"),
	p("http", "HTTP Request", "Developer Tools", "none"),
	p("http-oauth2", "HTTP OAuth2", "Developer Tools", "oauth2"),
	p("webhook", "Webhook", "Developer Tools", "none"),
	p("graphql", "GraphQL", "Developer Tools", "none"),
	p("soap", "SOAP", "Developer Tools", "custom"),
	p("xml", "XML", "Developer Tools", "none"),
	p("json", "JSON", "Developer Tools", "none"),
	p("csv", "CSV", "Developer Tools", "none"),
	p("mysql", "MySQL", "Developer Tools", "custom"),
	p("postgres", "PostgreSQL", "Developer Tools", "custom"),
	p("mongodb", "MongoDB", "Developer Tools", "custom"),
	p("couchbase", "Couchbase", "Developer Tools", "custom"),
	p("snowflake", "Snowflake", "Developer Tools", "custom"),
	p("duckdb", "DuckDB", "Developer Tools", "none"),
	p("oracle-database", "Oracle Database", "Developer Tools", "custom"),
	p("surrealdb", "SurrealDB", "Developer Tools", "custom"),
	p("supabase", "Supabase", "Developer Tools", "custom"),
	p("rabbitmq", "RabbitMQ", "Developer Tools", "custom"),
	p("gcloud-pubsub", "Google Cloud Pub/Sub", "Developer Tools", "custom"),
	p("amazon-s3", "Amazon S3", "Developer Tools", "custom"),
	p("amazon-sqs", "Amazon SQS", "Developer Tools", "custom"),
	p("amazon-sns", "Amazon SNS", "Developer Tools", "custom"),
	p("azure-blob-storage", "Azure Blob Storage", "Developer Tools", "custom"),
	p("azure-communication-services", "Azure Communications", "Developer Tools", "api_key"),
	p("digital-ocean", "DigitalOcean", "Developer Tools", "none"),
	p("netlify", "Netlify", "Developer Tools", "oauth2"),
	p("browserless", "Browserless", "Developer Tools", "custom"),
	p("apify", "Apify", "Developer Tools", "custom"),
	p("sftp", "SFTP", "Developer Tools", "custom"),
	p("scrapeless", "Scrapeless", "Developer Tools", "api_key"),
	p("datadog", "Datadog", "Developer Tools", "custom"),
	p("segment", "Segment", "Developer Tools", "api_key"),
	p("posthog", "PostHog", "Developer Tools", "api_key"),
	p("mixpanel", "Mixpanel", "Developer Tools", "api_key"),
	p("logrocket", "LogRocket", "Developer Tools", "api_key"),
	p("pinecone", "Pinecone", "Developer Tools", "custom"),
	p("qdrant", "Qdrant", "Developer Tools", "custom"),
	p("confluence", "Confluence", "Developer Tools", "custom"),
	p("figma", "Figma", "Developer Tools", "oauth2"),
	p("zeplin", "Zeplin", "Developer Tools", "api_key"),
	p("backblaze", "Backblaze", "Developer Tools", "custom"),
	p("hashi-corp-vault", "HashiCorp Vault", "Developer Tools", "custom"),
	p("eth-name-service", "Ethereum Name Service", "Developer Tools", "api_key"),
	p("metabase", "Metabase", "Developer Tools", "custom"),
	p("tableau", "Tableau", "Developer Tools", "custom"),

	// ─── Productivity ──────────────────────────────────────
	p("schedule", "Schedule", "Productivity", "none"),
	p("delay", "Delay", "Productivity", "none"),
	p("store", "Store", "Productivity", "none"),
	p("forms", "Forms", "Productivity", "none"),
	p("manual-trigger", "Manual Trigger", "Productivity", "none"),
	p("subflows", "Subflows", "Productivity", "none"),
	p("tables", "Tables", "Productivity", "none"),
	p("tags", "Tags", "Productivity", "none"),
	p("connections", "Connections", "Productivity", "none"),
	p("approval", "Approval", "Productivity", "none"),
	p("data-mapper", "Data Mapper", "Productivity", "none"),
	p("data-summarizer", "Data Summarizer", "Productivity", "none"),
	p("flow-helper", "Flow Helper", "Productivity", "none"),
	p("flow-parser", "Flow Parser", "Productivity", "api_key"),
	p("file-helper", "File Helper", "Productivity", "none"),
	p("image-helper", "Image Helper", "Productivity", "none"),
	p("text-helper", "Text Helper", "Productivity", "none"),
	p("date-helper", "Date Helper", "Productivity", "none"),
	p("math-helper", "Math Helper", "Productivity", "none"),
	p("qrcode", "QR Code", "Productivity", "none"),
	p("barcode-lookup", "Barcode Lookup", "Productivity", "api_key"),
	p("pdf", "PDF", "Productivity", "none"),
	p("crypto", "Crypto", "Productivity", "none"),
	p("queue", "Queue", "Productivity", "none"),
	p("todos", "Todos", "Productivity", "none"),
	p("time-ops", "Time Ops", "Productivity", "api_key"),
	p("mycase-piece", "MyCase", "Productivity", "oauth2"),
	p("ninox", "Ninox", "Productivity", "api_key"),

	// ─── Finance & Accounting ──────────────────────────────
	p("quickbooks", "QuickBooks", "Finance & Accounting", "oauth2"),
	p("xero", "Xero", "Finance & Accounting", "oauth2"),
	p("zoho-books", "Zoho Books", "Finance & Accounting", "oauth2"),
	p("zoho-invoice", "Zoho Invoice", "Finance & Accounting", "oauth2"),
	p("invoiceninja", "Invoice Ninja", "Finance & Accounting", "custom"),
	p("just-invoice", "Just Invoice", "Finance & Accounting", "api_key"),
	p("mooninvoice", "Moon Invoice", "Finance & Accounting", "custom"),
	p("bokio", "Bokio", "Finance & Accounting", "custom"),
	p("bexio", "Bexio", "Finance & Accounting", "oauth2"),
	p("quaderno", "Quaderno", "Finance & Accounting", "custom"),
	p("zuora", "Zuora", "Finance & Accounting", "custom"),
	p("netsuite", "NetSuite", "Finance & Accounting", "custom"),
	p("splitwise", "Splitwise", "Finance & Accounting", "api_key"),
	p("sap-ariba", "SAP Ariba", "Finance & Accounting", "custom"),
	p("binance", "Binance", "Finance & Accounting", "none"),
	p("checkout", "Checkout.com", "Finance & Accounting", "api_key"),

	// ─── Cloud Storage ─────────────────────────────────────
	p("dropbox", "Dropbox", "Cloud Storage", "oauth2"),
	p("box", "Box", "Cloud Storage", "oauth2"),
	p("cloudinary", "Cloudinary", "Cloud Storage", "custom"),
	p("cloudconvert", "CloudConvert", "Cloud Storage", "oauth2"),

	// ─── HR & Recruitment ──────────────────────────────────
	p("bamboohr", "BambooHR", "HR & Recruitment", "custom"),
	p("harvest", "Harvest", "HR & Recruitment", "oauth2"),
	p("clockify", "Clockify", "HR & Recruitment", "api_key"),
	p("clockodo", "Clockodo", "HR & Recruitment", "custom"),
	p("kimai", "Kimai", "HR & Recruitment", "custom"),
	p("workable", "Workable", "HR & Recruitment", "api_key"),
	p("omnihr", "OmniHR", "HR & Recruitment", "custom"),
	p("skyprep", "SkyPrep", "HR & Recruitment", "api_key"),
	p("toggl-track", "Toggl Track", "HR & Recruitment", "api_key"),

	// ─── Forms & Surveys ───────────────────────────────────
	p("typeform", "Typeform", "Forms & Surveys", "oauth2"),
	p("jotform", "Jotform", "Forms & Surveys", "custom"),
	p("tally", "Tally", "Forms & Surveys", "none"),
	p("fillout-forms", "Fillout Forms", "Forms & Surveys", "api_key"),
	p("cognito-forms", "Cognito Forms", "Forms & Surveys", "api_key"),
	p("formstack", "Formstack", "Forms & Surveys", "oauth2"),
	p("formspark", "Formspark", "Forms & Surveys", "none"),
	p("formsite", "Formsite", "Forms & Surveys", "none"),
	p("formitable", "Formitable", "Forms & Surveys", "api_key"),
	p("surveymonkey", "SurveyMonkey", "Forms & Surveys", "oauth2"),
	p("formbricks", "Formbricks", "Forms & Surveys", "custom"),
	p("youform", "Youform", "Forms & Surveys", "api_key"),
	p("kizeo-forms", "Kizeo Forms", "Forms & Surveys", "api_key"),
	p("opnform", "OpnForm", "Forms & Surveys", "custom"),
	p("wufoo", "Wufoo", "Forms & Surveys", "custom"),
	p("feathery", "Feathery", "Forms & Surveys", "api_key"),
	p("videoask", "VideoAsk", "Forms & Surveys", "oauth2"),
	p("paperform", "Paperform", "Forms & Surveys", "api_key"),
	p("gravityforms", "Gravity Forms", "Forms & Surveys", "none"),

	// ─── CMS & Website ─────────────────────────────────────
	p("wordpress", "WordPress", "CMS & Website", "custom"),
	p("webflow", "Webflow", "CMS & Website", "oauth2"),
	p("contentful", "Contentful", "CMS & Website", "custom"),
	p("ghostcms", "Ghost CMS", "CMS & Website", "custom"),
	p("drupal", "Drupal", "CMS & Website", "custom"),
	p("bubble", "Bubble", "CMS & Website", "none"),
	p("softr", "Softr", "CMS & Website", "api_key"),
	p("datocms", "DatoCMS", "CMS & Website", "custom"),
	p("brilliant-directories", "Brilliant Directories", "CMS & Website", "custom"),
	p("totalcms", "TotalCMS", "CMS & Website", "custom"),
	p("beamer", "Beamer", "CMS & Website", "api_key"),
	p("bettermode", "Bettermode", "CMS & Website", "custom"),

	// ─── Documents & Signatures ────────────────────────────
	p("docusign", "DocuSign", "Documents & Signatures", "oauth2"),
	p("pandadoc", "PandaDoc", "Documents & Signatures", "api_key"),
	p("documerge", "DocuMerge", "Documents & Signatures", "api_key"),
	p("simplepdf", "SimplePDF", "Documents & Signatures", "none"),
	p("esignatures", "eSignatures", "Documents & Signatures", "api_key"),
	p("signrequest", "SignRequest", "Documents & Signatures", "api_key"),
	p("documentpro", "DocumentPro", "Documents & Signatures", "api_key"),
	p("parseur", "Parseur", "Documents & Signatures", "api_key"),
	p("parser-expert", "Parser Expert", "Documents & Signatures", "api_key"),
	p("pdf-co", "PDF.co", "Documents & Signatures", "api_key"),
	p("pdfmonkey", "PDFMonkey", "Documents & Signatures", "api_key"),
	p("apitemplate-io", "APITemplate.io", "Documents & Signatures", "custom"),

	// ─── Automation & Utilities ────────────────────────────
	p("activepieces", "Activepieces", "Automation & Utilities", "custom"),
	p("generatebanners", "Generate Banners", "Automation & Utilities", "basic"),
	p("placid", "Placid", "Automation & Utilities", "api_key"),
	p("robolly", "Robolly", "Automation & Utilities", "api_key"),
	p("peekshot", "Peekshot", "Automation & Utilities", "api_key"),
	p("chartly", "Chartly", "Automation & Utilities", "api_key"),
	p("insta-charts", "InstaCharts", "Automation & Utilities", "oauth2"),
	p("bannerbear", "Bannerbear", "Automation & Utilities", "api_key"),
	p("short-io", "Short.io", "Automation & Utilities", "custom"),
	p("bitly", "Bitly", "Automation & Utilities", "custom"),
	p("cal-com", "Cal.com", "Automation & Utilities", "api_key"),
	p("calendly", "Calendly", "Automation & Utilities", "api_key"),
	p("acuity-scheduling", "Acuity Scheduling", "Automation & Utilities", "oauth2"),
	p("tidycal", "TidyCal", "Automation & Utilities", "api_key"),
	p("bookedin", "BookedIn", "Automation & Utilities", "api_key"),
	p("simplybookme", "SimplyBook.me", "Automation & Utilities", "custom"),
	p("lets-calendar", "Lets Calendar", "Automation & Utilities", "custom"),
	p("youcanbookme", "YouCanBook.me", "Automation & Utilities", "api_key"),
	p("oncehub", "OnceHub", "Automation & Utilities", "api_key"),
	p("zoom", "Zoom", "Automation & Utilities", "oauth2"),
	p("sessions-us", "Sessions.us", "Automation & Utilities", "api_key"),
	p("okta", "Okta", "Automation & Utilities", "custom"),
	p("cyberark", "CyberArk", "Automation & Utilities", "custom"),
	p("service-now", "ServiceNow", "Automation & Utilities", "custom"),
	p("odoo", "Odoo", "Automation & Utilities", "custom"),
	p("knack", "Knack", "Automation & Utilities", "custom"),
	p("kissflow", "KissFlow", "Automation & Utilities", "custom"),
	p("systeme-io", "Systeme.io", "Automation & Utilities", "api_key"),
	p("clickfunnels", "ClickFunnels", "Automation & Utilities", "custom"),
	p("lightfunnels", "LightFunnels", "Automation & Utilities", "oauth2"),
	p("poper", "Poper", "Automation & Utilities", "none"),
	p("lokalise", "Lokalise", "Automation & Utilities", "api_key"),
	p("webling", "Webling", "Automation & Utilities", "custom"),
	p("actualbudget", "Actual Budget", "Automation & Utilities", "custom"),
	p("ampeco", "Ampeco", "Automation & Utilities", "custom"),
	p("certopus", "Certopus", "Automation & Utilities", "api_key"),
	p("circle", "Circle", "Automation & Utilities", "api_key"),
	p("clicdata", "ClicData", "Automation & Utilities", "none"),
	p("cloutly", "Cloutly", "Automation & Utilities", "api_key"),
	p("cody", "Cody", "Automation & Utilities", "api_key"),
	p("dittofeed", "Dittofeed", "Automation & Utilities", "custom"),
	p("gameball", "Gameball", "Automation & Utilities", "api_key"),
	p("gamma", "Gamma", "Automation & Utilities", "custom"),
	p("giftbit", "Giftbit", "Automation & Utilities", "api_key"),
	p("gistly", "Gistly", "Automation & Utilities", "api_key"),
	p("heartbeat", "Heartbeat", "Automation & Utilities", "api_key"),
	p("katana", "Katana", "Automation & Utilities", "api_key"),
	p("livesession", "LiveSession", "Automation & Utilities", "api_key"),
	p("matomo", "Matomo", "Automation & Utilities", "custom"),
	p("mem", "Mem", "Automation & Utilities", "api_key"),
	p("motion", "Motion", "Automation & Utilities", "api_key"),
	p("motiontools", "MotionTools", "Automation & Utilities", "api_key"),
	p("onfleet", "Onfleet", "Automation & Utilities", "api_key"),
	p("presentation", "Presenton", "Automation & Utilities", "api_key"),
	p("respaid", "Respaid", "Automation & Utilities", "api_key"),
	p("saastic", "Saastic", "Automation & Utilities", "api_key"),
	p("seek-table", "Seek Table", "Automation & Utilities", "api_key"),
	p("serp-api", "SERP API", "Automation & Utilities", "api_key"),
	p("serpstat", "Serpstat", "Automation & Utilities", "api_key"),
	p("socialkit", "SocialKit", "Automation & Utilities", "api_key"),
	p("sperse", "Sperse", "Automation & Utilities", "custom"),
	p("swarmnode", "SwarmNode", "Automation & Utilities", "api_key"),
	p("talkable", "Talkable", "Automation & Utilities", "custom"),
	p("thankster", "Thankster", "Automation & Utilities", "api_key"),
	p("tidely", "Tidely", "Automation & Utilities", "api_key"),
	p("timelines-ai", "Timelines AI", "Automation & Utilities", "api_key"),
	p("tiny-talk-ai", "Tiny Talk AI", "Automation & Utilities", "api_key"),
	p("tl-dv", "tl;dv", "Automation & Utilities", "api_key"),
	p("truelayer", "TrueLayer", "Automation & Utilities", "oauth2"),
	p("twin-labs", "Twin Labs", "Automation & Utilities", "api_key"),
	p("uscreen", "Uscreen", "Automation & Utilities", "api_key"),
	p("vadoo-ai", "Vadoo AI", "Automation & Utilities", "api_key"),
	p("valyu", "Valyu", "Automation & Utilities", "api_key"),
	p("vero", "Vero", "Automation & Utilities", "api_key"),
	p("vidlab7", "VidLab7", "Automation & Utilities", "api_key"),
	p("village", "Village", "Automation & Utilities", "api_key"),
	p("visible", "Visible", "Automation & Utilities", "api_key"),
	p("vouchery-io", "Vouchery.io", "Automation & Utilities", "api_key"),
	p("waitwhile", "Waitwhile", "Automation & Utilities", "api_key"),
	p("wedof", "Wedof", "Automation & Utilities", "api_key"),
	p("week-done", "Weekdone", "Automation & Utilities", "oauth2"),
	p("what-converts", "WhatConverts", "Automation & Utilities", "custom"),
	p("whatsable", "Whatsable", "Automation & Utilities", "api_key"),
	p("wootric", "Wootric", "Automation & Utilities", "oauth2"),
	p("zagomail", "Zagomail", "Automation & Utilities", "api_key"),
	p("zendesk-sell", "Zendesk Sell", "Automation & Utilities", "custom"),
	p("zerobounce", "ZeroBounce", "Automation & Utilities", "api_key"),
	p("zoo", "Zoo", "Automation & Utilities", "api_key"),
	p("zoho-bookings", "Zoho Bookings", "Automation & Utilities", "oauth2"),
	p("zoho-desk", "Zoho Desk", "Automation & Utilities", "oauth2"),
	p("base44", "Base44", "Automation & Utilities", "custom"),
	p("blockscout", "Blockscout", "Automation & Utilities", "none"),
	p("browse-ai", "Browse AI", "Automation & Utilities", "api_key"),
	p("bumpups", "BumpUps", "Automation & Utilities", "api_key"),
	p("bursty-ai", "Bursty AI", "Automation & Utilities", "api_key"),
	p("captain-data", "Captain Data", "Automation & Utilities", "custom"),
	p("chain-aware", "Chain Aware", "Automation & Utilities", "api_key"),
	p("chainalysis-api", "Chainalysis", "Automation & Utilities", "api_key"),
	p("chaindesk", "Chaindesk", "Automation & Utilities", "api_key"),
	p("chargekeep", "ChargeKeep", "Automation & Utilities", "custom"),
	p("clearoutphone", "ClearoutPhone", "Automation & Utilities", "api_key"),
	p("cometapi", "CometAPI", "Automation & Utilities", "api_key"),
	p("contiguity", "Contiguity", "Automation & Utilities", "api_key"),
	p("cryptolens", "Cryptolens", "Automation & Utilities", "api_key"),
	p("dappier", "Dappier", "Automation & Utilities", "api_key"),
	p("dashworks", "Dashworks", "Automation & Utilities", "api_key"),
	p("datafuel", "DataFuel", "Automation & Utilities", "api_key"),
	p("digital-pilot", "Digital Pilot", "Automation & Utilities", "api_key"),
	p("dimo", "DIMO", "Automation & Utilities", "custom"),
	p("doctly", "Doctly", "Automation & Utilities", "api_key"),
	p("famulor", "Famulor", "Automation & Utilities", "api_key"),
	p("fathom", "Fathom", "Automation & Utilities", "api_key"),
	p("fellow", "Fellow", "Automation & Utilities", "custom"),
	p("flipando", "Flipando", "Automation & Utilities", "api_key"),
	p("fliqr-ai", "Fliqr AI", "Automation & Utilities", "api_key"),
	p("foreplay-co", "Foreplay", "Automation & Utilities", "api_key"),
	p("fountain", "Fountain", "Automation & Utilities", "custom"),
	p("fragment", "Fragment", "Automation & Utilities", "api_key"),
	p("free-agent", "FreeAgent", "Automation & Utilities", "oauth2"),
	p("gender-api", "Gender API", "Automation & Utilities", "api_key"),
	p("greenpt", "GreenPT", "Automation & Utilities", "api_key"),
	p("greip", "Greip", "Automation & Utilities", "api_key"),
	p("guidelite", "GuideLite", "Automation & Utilities", "api_key"),
	p("hastewire", "Hastewire", "Automation & Utilities", "api_key"),
	p("hedy", "Hedy", "Automation & Utilities", "api_key"),
	p("housecall-pro", "Housecall Pro", "Automation & Utilities", "api_key"),
	p("hystruct", "Hystruct", "Automation & Utilities", "api_key"),
	p("ibm-cognose", "IBM Cognos", "Automation & Utilities", "api_key"),
	p("image-router", "Image Router", "Automation & Utilities", "api_key"),
	p("influencers-club", "Influencers Club", "Automation & Utilities", "api_key"),
	p("instabase", "Instabase", "Automation & Utilities", "api_key"),
	p("kudosity", "Kudosity", "Automation & Utilities", "api_key"),
	p("leexi", "Leexi", "Automation & Utilities", "api_key"),
	p("linkup", "LinkUp", "Automation & Utilities", "api_key"),
	p("lucidya", "Lucidya", "Automation & Utilities", "api_key"),
	p("luxury-presence", "Luxury Presence", "Automation & Utilities", "api_key"),
	p("manus", "Manus", "Automation & Utilities", "api_key"),
	p("medullar", "Medullar", "Automation & Utilities", "api_key"),
	p("mempool-space", "Mempool Space", "Automation & Utilities", "none"),
	p("metatext", "Metatext", "Automation & Utilities", "api_key"),
	p("millionverifier", "MillionVerifier", "Automation & Utilities", "api_key"),
	p("neverbounce", "NeverBounce", "Automation & Utilities", "api_key"),
	p("nifty", "Nifty", "Automation & Utilities", "oauth2"),
	p("omni-co", "Omni.co", "Automation & Utilities", "api_key"),
	p("oneclickimpact", "OneClickImpact", "Automation & Utilities", "api_key"),
	p("opportify", "Opportify", "Automation & Utilities", "api_key"),
	p("orimon", "Orimon", "Automation & Utilities", "api_key"),
	p("pastebin", "Pastebin", "Automation & Utilities", "custom"),
	p("pastefy", "Pastefy", "Automation & Utilities", "custom"),
	p("phone-validator", "Phone Validator", "Automation & Utilities", "api_key"),
	p("pollybot-ai", "PollyBot AI", "Automation & Utilities", "custom"),
	p("reoon-verifier", "Reoon Verifier", "Automation & Utilities", "api_key"),
	p("simpliroute", "SimpliRoute", "Automation & Utilities", "api_key"),
	p("supadata", "Supadata", "Automation & Utilities", "api_key"),
	p("tenzo", "Tenzo", "Automation & Utilities", "none"),
	p("upgradechat", "UpgradeChat", "Automation & Utilities", "custom"),
	p("anyhook-graphql", "AnyHook GraphQL", "Automation & Utilities", "custom"),
	p("anyhook-websocket", "AnyHook WebSocket", "Automation & Utilities", "custom"),
	p("appfollow", "AppFollow", "Automation & Utilities", "api_key"),
	p("ask-handle", "Ask Handle", "Automation & Utilities", "api_key"),
	p("asknews", "AskNews", "Automation & Utilities", "api_key"),
	p("assembled", "Assembled", "Automation & Utilities", "api_key"),
	p("avoma", "Avoma", "Automation & Utilities", "api_key"),
	p("baremetrics", "Baremetrics", "Automation & Utilities", "none"),
	p("aminos", "Aminos", "Automation & Utilities", "custom"),
	p("activity", "Activity", "Automation & Utilities", "none"),
].sort((a, b) => a.displayName.localeCompare(b.displayName));

// ─── Lookup helpers ────────────────────────────────────

const catalogByName = new Map<string, PieceCatalogEntry>();
for (const entry of PIECE_CATALOG) {
	catalogByName.set(entry.name, entry);
}

/** Get a catalog entry by piece name */
export function getCatalogEntry(
	pieceName: string,
): PieceCatalogEntry | undefined {
	return catalogByName.get(pieceName);
}

/** Get all piece names in the catalog */
export function getAllPieceNames(): string[] {
	return PIECE_CATALOG.map((e) => e.name);
}

/** Get all unique categories */
export function getAllCategories(): PieceCategory[] {
	return [
		...new Set(PIECE_CATALOG.map((e) => e.category)),
	].sort() as PieceCategory[];
}

/** Get pieces filtered by category */
export function getPiecesByCategory(
	category: PieceCategory,
): PieceCatalogEntry[] {
	return PIECE_CATALOG.filter((e) => e.category === category);
}

/** Search pieces by name/displayName */
export function searchPieces(query: string): PieceCatalogEntry[] {
	const q = query.toLowerCase();
	return PIECE_CATALOG.filter(
		(e) =>
			e.name.includes(q) ||
			e.displayName.toLowerCase().includes(q) ||
			e.category.toLowerCase().includes(q),
	);
}

/** Total number of pieces in catalog */
export const TOTAL_PIECES = PIECE_CATALOG.length;

/**
 * Set of piece names that have NPM packages installed.
 * These pieces can be loaded at runtime and their actions can be inspected.
 * Pieces NOT in this set are catalog-only (metadata available but can't execute).
 */
export const INSTALLED_PIECES = new Set([
	"slack",
	"google-sheets",
	"gmail",
	"discord",
	"telegram-bot",
	"notion",
	"airtable",
	"openai",
	"google-drive",
	"http",
	"github",
	"stripe",
	"paypal",
	"hubspot",
	"mailchimp",
	"google-calendar",
	"dropbox",
	"trello",
	"asana",
	"jira-cloud",
	"sendgrid",
	"zoom",
	"twitter",
	"linkedin",
	"microsoft-teams",
	"microsoft-outlook",
	"salesforce",
	"shopify",
	"wordpress",
	"todoist",
	"clickup",
	"monday",
	"linear",
	"intercom",
	"freshdesk",
	"zendesk",
	"google-contacts",
	"google-forms",
	"google-docs",
	"google-slides",
	"google-tasks",
	"googlechat",
	"google-my-business",
	"google-cloud-storage",
	"google-search-console",
	"typeform",
	"twilio",
	"figma",
	"supabase",
	"postgres",
	"mysql",
	"csv",
	"rss",
	"schedule",
	"webhook",
	"data-mapper",
	"store",
	"connections",
	// ─── Phase 1: Microsoft 365 + Top OAuth2 Services ─────
	"microsoft-excel-365",
	"microsoft-onedrive",
	"microsoft-onenote",
	"microsoft-outlook-calendar",
	"microsoft-power-bi",
	"microsoft-sharepoint",
	"microsoft-todo",
	"microsoft-365-people",
	"microsoft-365-planner",
	"microsoft-dynamics-365-business-central",
	"youtube",
	"facebook-pages",
	"facebook-leads",
	"instagram-business",
	"reddit",
	"pinterest",
	"spotify",
	"vimeo",
	"twitch",
	"pipedrive",
	"zoho-crm",
	"activecampaign",
	"quickbooks",
	"xero",
	"square",
	"bigcommerce",
	"box",
	"pandadoc",
	"calendly",
	"webflow",
	"contentful",
	"gitlab",
	"confluence",
	"surveymonkey",
	"formstack",
	"bitly",
	"constant-contact",
	"campaign-monitor",
	"front",
	"help-scout",
	"wrike",
	"meistertask",
	"ticktick",
	"podio",
	"teamleader",
	"lever",
	"microsoft-dynamics-crm",
	"bigin-by-zoho",
	"harvest",
	"okta",

	// ─── Phase 2: AI/ML Services + Core Utilities ─────
	"claude",
	"google-gemini",
	"azure-openai",
	"deepseek",
	"groq",
	"grok-xai",
	"mistral-ai",
	"perplexity-ai",
	"open-router",
	"elevenlabs",
	"deepgram",
	"assemblyai",
	"stability-ai",
	"hugging-face",
	"deepl",
	"firecrawl",
	"tavily",
	"exa",
	"jina-ai",
	"runway",
	"heygen",
	"synthesia",
	"google-search",
	"hackernews",
	"bluesky",
	"mastodon",
	"pdf",
	"text-helper",
	"date-helper",
	"math-helper",
	"file-helper",
	"image-helper",
	"qrcode",
	"delay",
	"json",
	"xml",
	"data-summarizer",
	"flow-helper",
	"flow-parser",
	"crypto",
	"queue",
	"todos",
	"time-ops",
	"approval",
	"forms",
	"manual-trigger",
	"subflows",
	"tables",
	"tags",
	"barcode-lookup",

	// ─── Phase 3: Developer Tools + Databases + E-Commerce ─────
	"mongodb",
	"snowflake",
	"oracle-database",
	"surrealdb",
	"couchbase",
	"rabbitmq",
	"sftp",
	"gcloud-pubsub",
	"amazon-s3",
	"amazon-sqs",
	"amazon-sns",
	"azure-blob-storage",
	"azure-communication-services",
	"digital-ocean",
	"netlify",
	"browserless",
	"apify",
	"scrapeless",
	"datadog",
	"segment",
	"posthog",
	"mixpanel",
	"logrocket",
	"pinecone",
	"qdrant",
	"http-oauth2",
	"graphql",
	"soap",
	"zeplin",
	"backblaze",
	"hashi-corp-vault",
	"metabase",
	"tableau",
	"cloudinary",
	"cloudconvert",
	"woocommerce",
	"lemon-squeezy",
	"razorpay",
	"mollie",
	"saleor",
	"vtex",
	"shippo",
	"cashfree-payments",
	"cartloom",
	"billplz",
	"moonclerk",
	"pinch-payments",
	"quickzu",
	"paywhirl",

	// ─── Phase 4: Email Marketing + Communication ─────
	"sendinblue",
	"mailjet",
	"mailer-lite",
	"convertkit",
	"customer-io",
	"drip",
	"lemlist",
	"beehiiv",
	"vbout",
	"emailoctopus",
	"maileroo",
	"instantly-ai",
	"reachinbox",
	"sendpulse",
	"amazon-ses",
	"smtp",
	"sendfox",
	"smaily",
	"nuelink",
	"tarvent",
	"resend",
	"sender",
	"sendy",
	"acumbamail",
	"mailchain",
	"mailercheck",
	"smoove",
	"woodpecker",
	"zoho-campaigns",
	"zoho-mail",
	"imap",
	"mattermost",
	"whatsapp",
	"line",
	"crisp",
	"missive",
	"manychat",
	"respond-io",
	"chatbase",
	"messagebird",
	"clicksend",
	"open-phone",
	"voipstudio",
	"ntfy",
	"pushbullet",
	"pushover",
	"matrix",
	"discourse",
	"gotify",
	"bonjoro",

	// ─── Phase 5: CRM + Project Management + Finance + HR ─────
	"close",
	"copper",
	"freshsales",
	"attio",
	"apollo",
	"ashby",
	"kommo",
	"insightly",
	"capsule-crm",
	"folk",
	"lead-connector",
	"moxie-crm",
	"wealthbox",
	"hunter",
	"clearout",
	"lusha",
	"predict-leads",
	"vtiger",
	"lofty",
	"fireberry",
	"baserow",
	"smartsheet",
	"smartsuite",
	"coda",
	"taskade",
	"nocodb",
	"retable",
	"apitable",
	"bika",
	"grist",
	"quickbase",
	"flowlu",
	"frame",
	"productboard",
	"teamwork",
	"zoho-books",
	"zoho-invoice",
	"invoiceninja",
	"bokio",
	"bexio",
	"quaderno",
	"zuora",
	"netsuite",
	"splitwise",
	"sap-ariba",
	"bamboohr",
	"clockify",
	"clockodo",
	"kimai",
	"workable",

	// ─── Phase 6: Forms + CMS + Documents + Remaining Comms ─────
	"jotform",
	"tally",
	"fillout-forms",
	"cognito-forms",
	"formspark",
	"formsite",
	"formitable",
	"formbricks",
	"youform",
	"kizeo-forms",
	"opnform",
	"wufoo",
	"feathery",
	"videoask",
	"paperform",
	"ghostcms",
	"drupal",
	"bubble",
	"softr",
	"datocms",
	"brilliant-directories",
	"totalcms",
	"beamer",
	"bettermode",
	"documerge",
	"simplepdf",
	"esignatures",
	"signrequest",
	"documentpro",
	"parseur",
	"parser-expert",
	"pdf-co",
	"pdfmonkey",
	"omnihr",
	"skyprep",
	"toggl-track",
	"just-invoice",
	"mooninvoice",
	"chatfly",
	"chatling",
	"chatnode",
	"chat-data",
	"chat-aid",
	"chatsistant",
	"wonderchat",
	"pylon",
	"heymarket-sms",
	"octopush-sms",
	"smsmode",
	"instasent",

	// ─── Phase 7: AI/ML Batch 2 ─────
	"stable-diffusion-webui",
	"gladia",
	"eden-ai",
	"clarifai",
	"flowise",
	"afforai",
	"aidbase",
	"aianswer",
	"ai",
	"alt-text-ai",
	"alttextify",
	"copy-ai",
	"textcortex-ai",
	"detecting-ai",
	"gptzero-detect-ai",
	"straico",
	"contextual-ai",
	"mind-studio",
	"devin",
	"cursor",
	"griptape",
	"letta",
	"mcp",
	"localai",
	"comfyicu",
	"jogg-ai",
	"vidnoz",
	"camb-ai",
	"murf-api",
	"bolna",
	"agentx",
	"air-ops",
	"airparser",
	"airtop",
	"alai",
	"easy-peasy-ai",
	"echowin",
	"extracta-ai",
	"fireflies-ai",
	"insighto-ai",
	"kallabot-ai",
	"leap-ai",
	"llmrails",
	"magical-api",
	"magicslides",
	"meetgeek-ai",
	"mindee",
	"moveo-ai",
	"openmic-ai",
	"personal-ai",

	// ─── Phase 8: AI/ML Batch 3 + Scheduling/Security ─────
	"phantombuster",
	"photoroom",
	"predis-ai",
	"prompthub",
	"promptmate",
	"raia-ai",
	"rapidtext-ai",
	"recall-ai",
	"retell-ai",
	"retune",
	"returning-ai",
	"roe-ai",
	"runware",
	"scenario",
	"scrapegrapghai",
	"sitespeakai",
	"skyvern",
	"slidespeak",
	"vlm-run",
	"webscraping-ai",
	"writesonic-bulk",
	"denser-ai",
	"docsbot",
	"customgpt",
	"hume-ai",
	"seven",
	"krisp-call",
	"autocalls",
	"activepieces",
	"generatebanners",
	"placid",
	"robolly",
	"peekshot",
	"chartly",
	"insta-charts",
	"bannerbear",
	"short-io",
	"cal-com",
	"acuity-scheduling",
	"tidycal",
	"bookedin",
	"simplybookme",
	"lets-calendar",
	"youcanbookme",
	"oncehub",
	"sessions-us",
	"cyberark",
	"service-now",
	"odoo",

	// ─── Phase 9: Automation & Utilities Batch 1 ─────
	"knack",
	"kissflow",
	"systeme-io",
	"clickfunnels",
	"lightfunnels",
	"poper",
	"lokalise",
	"webling",
	"actualbudget",
	"ampeco",
	"certopus",
	"circle",
	"clicdata",
	"cloutly",
	"cody",
	"dittofeed",
	"gameball",
	"gamma",
	"giftbit",
	"gistly",
	"heartbeat",
	"katana",
	"livesession",
	"matomo",
	"mem",
	"motion",
	"motiontools",
	"onfleet",
	"respaid",
	"saastic",
	"seek-table",
	"serp-api",
	"serpstat",
	"socialkit",
	"sperse",
	"swarmnode",
	"talkable",
	"thankster",
	"tidely",
	"timelines-ai",
	"tiny-talk-ai",
	"tl-dv",
	"truelayer",
	"twin-labs",
	"uscreen",
	"vadoo-ai",
	"valyu",
	"vero",
	"vidlab7",

	// ─── Phase 10: Automation & Utilities Batch 2 ─────
	"village",
	"visible",
	"vouchery-io",
	"waitwhile",
	"wedof",
	"week-done",
	"what-converts",
	"whatsable",
	"wootric",
	"zagomail",
	"zendesk-sell",
	"zerobounce",
	"zoo",
	"zoho-bookings",
	"zoho-desk",
	"base44",
	"blockscout",
	"browse-ai",
	"bumpups",
	"bursty-ai",
	"captain-data",
	"chain-aware",
	"chainalysis-api",
	"chaindesk",
	"chargekeep",
	"clearoutphone",
	"cometapi",
	"contiguity",
	"cryptolens",
	"dappier",
	"dashworks",
	"datafuel",
	"digital-pilot",
	"dimo",
	"doctly",
	"famulor",
	"fathom",
	"fellow",
	"flipando",
	"fliqr-ai",
	"foreplay-co",
	"fountain",
	"fragment",
	"free-agent",
	"gender-api",
	"greenpt",
	"greip",
	"guidelite",
	"hastewire",
	"hedy",

	// ─── Phase 11: Final Batch + Extras ─────
	"manus",
	"medullar",
	"mempool-space",
	"metatext",
	"millionverifier",
	"neverbounce",
	"nifty",
	"omni-co",
	"oneclickimpact",
	"opportify",
	"orimon",
	"pastebin",
	"pastefy",
	"phone-validator",
	"pollybot-ai",
	"reoon-verifier",
	"simpliroute",
	"supadata",
	"tenzo",
	"upgradechat",
	"anyhook-graphql",
	"anyhook-websocket",
	"appfollow",
	"ask-handle",
	"asknews",
	"assembled",
	"avoma",
	"baremetrics",
	"aminos",
	"activity",
	"agent",
	"aircall",
	"apitemplate-io",
	"binance",
	"blackbaud",
	"bloomerang",
	"checkout",
	"dumpling-ai",
	"dust",
	"eth-name-service",
	"gravityforms",
	"linka",
	"mautic",
	"mycase-piece",
	"ninox",
	"plausible",
	"presentation",
	"qwilr",
	"rounded-studio",
	"salsa",
]);

/** Check if a piece has an NPM package installed */
export function isInstalledPiece(pieceName: string): boolean {
	return INSTALLED_PIECES.has(pieceName);
}

// ─── Per-category colors for integration nodes ─────────

const CATEGORY_COLORS: Record<PieceCategory, string> = {
	"AI & ML": "hsl(270, 70%, 60%)",
	"Automation & Utilities": "hsl(38, 85%, 52%)",
	"CMS & Website": "hsl(185, 75%, 48%)",
	"CRM & Sales": "hsl(340, 72%, 55%)",
	"Cloud Storage": "hsl(200, 82%, 55%)",
	Communication: "hsl(230, 68%, 60%)",
	"Developer Tools": "hsl(150, 65%, 45%)",
	"Documents & Signatures": "hsl(45, 70%, 55%)",
	"E-Commerce": "hsl(22, 88%, 55%)",
	"Email & Marketing": "hsl(10, 78%, 56%)",
	"Finance & Accounting": "hsl(85, 65%, 48%)",
	"Forms & Surveys": "hsl(165, 65%, 45%)",
	"Google Workspace": "hsl(217, 82%, 58%)",
	"HR & Recruitment": "hsl(320, 68%, 55%)",
	"Microsoft 365": "hsl(207, 72%, 52%)",
	Productivity: "hsl(255, 62%, 60%)",
	"Project Management": "hsl(290, 62%, 55%)",
	"Social Media": "hsl(350, 72%, 55%)",
};

/** Get the category-based color for an integration piece */
export function getPieceCategoryColor(pieceName: string): string | null {
	const entry = getCatalogEntry(pieceName);
	if (!entry) return null;
	return CATEGORY_COLORS[entry.category] ?? null;
}
