-- Scene Template Seeds for Feature Bank
-- Generated by tools/generate-scene-seed-sql.mjs
-- Run via: psql -U vibexe -d vibexe -f tools/seed-scene-templates.sql

DELETE FROM feature_bank_snippets WHERE id IN ('platformer-base', 'runner-base', 'puzzle-base', 'shooter-base');

INSERT INTO feature_bank_snippets (id, name, description, category, type, engine, version, keywords, parameters, dependencies, genres, code, is_built_in, is_verified)
VALUES (
  'platformer-base',
  'Platformer Base Scene',
  'Complete platformer with 18 visual layers, platforms, coins, enemies, physics, camera follow, seeded PRNG level generation',
  'Scene Templates',
  'scene',
  '2d',
  '1.0.0',
  '["platformer","side-scroller","jump","platform","physics"]'::jsonb,
  '[{"name":"theme","type":"string","default":"forest"},{"name":"seed","type":"number","default":1234},{"name":"gravity","type":"number","default":980},{"name":"moveSpeed","type":"number","default":280},{"name":"jumpForce","type":"number","default":520},{"name":"worldWidth","type":"number","default":4000},{"name":"platformCount","type":"number","default":11},{"name":"coinCount","type":"number","default":27},{"name":"enemyCount","type":"number","default":6},{"name":"levelShape","type":"string","default":"flat-wide"},{"name":"doubleJump","type":"boolean","default":true},{"name":"wallSlide","type":"boolean","default":false},{"name":"lives","type":"number","default":3}]'::jsonb,
  '[]'::jsonb,
  '["platformer"]'::jsonb,
  '// Auto-composed base scene template: platformer
// Placeholder tokens are replaced at generation time by scene-generator.ts
import { Engine2D, GameScene, createGame2D, loadAssets, JuiceSystem } from "../engine/core";
import { createBody, createStaticBody, createOneWayPlatform, PhysicsWorld, CharacterController } from "../engine/physics";
import { createAmbientEffect, createSnowEffect, createRainEffect, getThemeEffects, onJumpDust, onLandImpact, onCollectSparkle, onDeathExplosion } from "../engine/effects";
import { PALETTES, lerpColor, setNoiseSeed, drawSkyGradient, drawStars, drawMountainRange, drawCloud, drawTree, drawGroundStrip, drawPlatformBlock, drawPlayerCharacter, drawCoinToken, drawEnemySlime, drawHeart, drawVignette, drawAtmosphericFog, drawLSystemTree, TREE_PRESETS, drawPointLight, createLightingLayer, createWaterSurface, createLavaSurface } from "../config/assets";
import { _loadSpriteLib, _sheetCache } from "../utils/media-stock";

const PIXI = (window as any).PIXI;

// ======================== SEEDED PRNG (Mulberry32) ========================
var _seed = __SEED__;
function _rng() { _seed |= 0; _seed = _seed + 0x6D2B79F5 | 0; var t = Math.imul(_seed ^ _seed >>> 15, 1 | _seed); t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t; return ((t ^ t >>> 14) >>> 0) / 4294967296; }
function _rngRange(min: number, max: number) { return min + _rng() * (max - min); }
function _rngInt(min: number, max: number) { return Math.floor(_rngRange(min, max + 1)); }
function _rngPick<T>(arr: T[]): T { return arr[_rngInt(0, arr.length - 1)]; }

// ======================== CONFIGURATION ========================
var THEME = ''__THEME__'';
var PAL = PALETTES[THEME] || PALETTES.forest;

var CONFIG = {
  gravity: __GRAVITY__,
  worldWidth: __WORLD_WIDTH__,
  worldHeight: 900,
  groundY: 680,
  playerSize: 48,
  playerStartX: 250,
  moveSpeed: __MOVE_SPEED__,
  jumpForce: __JUMP_FORCE__,
  coinRadius: 10,
  enemySize: 44,
  enemySpeed: __ENEMY_SPEED__,
  lives: __LIVES__,
  platformCount: __PLATFORM_COUNT__,
  enemyCount: __ENEMY_COUNT__,
  coinCount: __COIN_COUNT__,
  levelShape: ''__LEVEL_SHAPE__'' as ''flat-wide'' | ''staircase-ascending'' | ''valley-bowl'' | ''hilly-undulating'',
  doubleJump: __DOUBLE_JUMP__,
  wallSlide: __WALL_SLIDE__,
};

// ======================== LEVEL GENERATORS ========================
function _generatePlatformY(index: number, total: number): number {
  var t = index / Math.max(total - 1, 1);
  var minY = CONFIG.groundY - 360;
  var maxY = CONFIG.groundY - 80;
  switch (CONFIG.levelShape) {
    case ''staircase-ascending'':
      return maxY - t * (maxY - minY) + _rngRange(-20, 20);
    case ''valley-bowl'':
      var bowl = Math.abs(t - 0.5) * 2;
      return minY + bowl * (maxY - minY) * 0.6 + _rngRange(-15, 15);
    case ''hilly-undulating'':
      return minY + (maxY - minY) * (0.5 + 0.4 * Math.sin(t * Math.PI * 3)) + _rngRange(-20, 20);
    default:
      return _rngRange(minY, maxY);
  }
}

function _generatePlatforms() {
  var plats = [];
  var spacing = (CONFIG.worldWidth - 600) / CONFIG.platformCount;
  for (var i = 0; i < CONFIG.platformCount; i++) {
    plats.push({
      x: 350 + i * spacing + _rngRange(-spacing * 0.2, spacing * 0.2),
      y: _generatePlatformY(i, CONFIG.platformCount),
      w: _rngInt(120, 200),
    });
  }
  return plats;
}

function _generateCoins(platforms: { x: number; y: number; w: number }[]) {
  var coins: { x: number; y: number }[] = [];
  var onPlatCount = Math.floor(CONFIG.coinCount * 0.6);
  var groundCount = CONFIG.coinCount - onPlatCount;
  for (var i = 0; i < onPlatCount; i++) {
    var p = platforms[_rngInt(0, platforms.length - 1)];
    coins.push({ x: p.x + _rngRange(-p.w * 0.3, p.w * 0.3), y: p.y - _rngRange(25, 45) });
  }
  for (var j = 0; j < groundCount; j++) {
    coins.push({ x: _rngRange(300, CONFIG.worldWidth - 200), y: CONFIG.groundY - 40 });
  }
  return coins;
}

function _generateEnemies() {
  var enemies: { x: number; range: number }[] = [];
  var spacing = (CONFIG.worldWidth - 400) / CONFIG.enemyCount;
  for (var i = 0; i < CONFIG.enemyCount; i++) {
    enemies.push({
      x: 500 + i * spacing + _rngRange(-spacing * 0.2, spacing * 0.2),
      range: _rngInt(80, 180),
    });
  }
  return enemies;
}

function _generateDecorations() {
  var count = _rngInt(10, 18);
  var decs: { x: number; type: number; size: number; flip: boolean }[] = [];
  var spacing = CONFIG.worldWidth / count;
  for (var i = 0; i < count; i++) {
    decs.push({
      x: i * spacing + _rngRange(20, spacing - 20),
      type: _rngInt(0, 3),
      size: _rngRange(1.8, 3.2),
      flip: _rng() > 0.5,
    });
  }
  return decs;
}

// ======================== THEME-SPECIFIC DRAWING ========================
function _drawDecoration(type: number, size: number): any {
  var g = new PIXI.Graphics();
  var s = size;
  switch (THEME) {
    case ''volcanic'':
      if (type === 0) { g.beginFill(0xff3300, 0.8); g.drawEllipse(0, 0, 30 * s, 8 * s); g.endFill(); g.beginFill(0xff6600, 0.6); g.drawEllipse(0, -2, 20 * s, 5 * s); g.endFill(); g.beginFill(0xffaa00, 0.4); g.drawEllipse(0, -3, 10 * s, 3 * s); g.endFill(); }
      else if (type === 1) { g.beginFill(0x3a2a1a); g.moveTo(-8*s, 0); g.lineTo(8*s, 0); g.lineTo(4*s, -20*s); g.lineTo(-4*s, -20*s); g.endFill(); g.beginFill(0x554433); g.drawCircle(0, -20*s, 6*s); g.endFill(); g.beginFill(0xff4400, 0.5); g.drawCircle(0, -20*s, 3*s); g.endFill(); }
      else if (type === 2) { g.beginFill(0x1a1a2a); g.moveTo(0, -35*s); g.lineTo(8*s, 0); g.lineTo(-8*s, 0); g.endFill(); g.beginFill(0x2a2a4a); g.moveTo(6*s, -25*s); g.lineTo(12*s, 0); g.lineTo(2*s, 0); g.endFill(); g.beginFill(0xff4400, 0.3); g.moveTo(0, -30*s); g.lineTo(3*s, -10*s); g.lineTo(-3*s, -10*s); g.endFill(); }
      else { g.beginFill(0x4a3a2a); g.drawRoundedRect(-15*s, -12*s, 30*s, 12*s, 4); g.endFill(); g.beginFill(0x5a4a3a); g.drawRoundedRect(-10*s, -18*s, 20*s, 8*s, 3); g.endFill(); g.lineStyle(1, 0xff4400, 0.6); g.moveTo(-5*s, -2*s); g.lineTo(0, -10*s); g.lineTo(5*s, -4*s); }
      break;
    case ''arctic'':
      if (type === 0) { g.beginFill(0x99ddff, 0.8); g.moveTo(0, -40*s); g.lineTo(6*s, -10*s); g.lineTo(0, 0); g.lineTo(-6*s, -10*s); g.endFill(); g.beginFill(0xbbeeFF, 0.5); g.moveTo(0, -35*s); g.lineTo(3*s, -12*s); g.lineTo(-3*s, -12*s); g.endFill(); g.beginFill(0xccffff, 0.6); g.moveTo(10*s, -25*s); g.lineTo(14*s, -10*s); g.lineTo(8*s, -10*s); g.endFill(); }
      else if (type === 1) { g.beginFill(0xddeeff, 0.9); g.drawEllipse(0, 0, 25*s, 10*s); g.endFill(); g.beginFill(0xeef4ff, 0.7); g.drawEllipse(5*s, -3*s, 15*s, 6*s); g.endFill(); }
      else if (type === 2) { g.beginFill(0x88bbdd); g.drawRoundedRect(-6*s, -45*s, 12*s, 45*s, 3); g.endFill(); g.beginFill(0xaaddee, 0.6); g.drawRoundedRect(-3*s, -42*s, 6*s, 38*s, 2); g.endFill(); g.beginFill(0x99ccee); g.drawCircle(0, -48*s, 8*s); g.endFill(); }
      else { for (var ic = 0; ic < 3; ic++) { var ix = (ic-1)*10*s; var ih = (20+ic*8)*s; g.beginFill(0xaaddff, 0.8); g.moveTo(ix-3*s, 0); g.lineTo(ix, -ih); g.lineTo(ix+3*s, 0); g.endFill(); } }
      break;
    case ''candy'':
      if (type === 0) { g.beginFill(0x886644); g.drawRect(-2*s, -40*s, 4*s, 40*s); g.endFill(); g.beginFill(0xff6699); g.drawCircle(0, -48*s, 12*s); g.endFill(); g.beginFill(0xffaacc, 0.6); g.drawCircle(-3*s, -50*s, 5*s); g.endFill(); g.lineStyle(2, 0xffffff, 0.5); g.arc(0, -48*s, 8*s, 0, Math.PI); g.lineStyle(0); }
      else if (type === 1) { g.beginFill(0xff3344); g.drawRoundedRect(-4*s, -35*s, 8*s, 35*s, 3); g.endFill(); for (var st = 0; st < 5; st++) { g.beginFill(0xffffff, 0.8); g.drawRect(-4*s, -35*s+st*14*s, 8*s, 4*s); g.endFill(); } g.beginFill(0xff3344); g.drawCircle(6*s, -35*s, 5*s); g.endFill(); }
      else if (type === 2) { g.beginFill(0x44cc88); g.drawEllipse(0, -12*s, 10*s, 14*s); g.endFill(); g.beginFill(0x44cc88); g.drawCircle(-6*s, -26*s, 5*s); g.drawCircle(6*s, -26*s, 5*s); g.endFill(); g.beginFill(0xffffff); g.drawCircle(-3*s, -14*s, 2*s); g.drawCircle(3*s, -14*s, 2*s); g.endFill(); g.beginFill(0x111111); g.drawCircle(-3*s, -14*s, 1); g.drawCircle(3*s, -14*s, 1); g.endFill(); }
      else { var sprColors = [0xff6699, 0x66ccff, 0xffcc33, 0x66ff99, 0xff66ff]; for (var sp = 0; sp < 8; sp++) { g.beginFill(sprColors[sp % sprColors.length]); g.drawRoundedRect(_rngRange(-15,15)*s, _rngRange(-8,0)*s, 6*s, 2*s, 1); g.endFill(); } }
      break;
    case ''space'':
      if (type === 0) { g.beginFill(0x555566); g.drawCircle(0, -15*s, 14*s); g.endFill(); g.beginFill(0x444455); g.drawCircle(-5*s, -18*s, 5*s); g.endFill(); g.beginFill(0x333344); g.drawCircle(6*s, -12*s, 4*s); g.endFill(); }
      else if (type === 1) { g.beginFill(0x44ff88, 0.8); g.moveTo(0,0); g.quadraticCurveTo(15*s,-20*s,5*s,-35*s); g.quadraticCurveTo(0,-25*s,0,0); g.endFill(); g.beginFill(0x88ffbb, 0.6); g.moveTo(0,0); g.quadraticCurveTo(-12*s,-18*s,-3*s,-30*s); g.quadraticCurveTo(0,-20*s,0,0); g.endFill(); g.beginFill(0xaaffdd); g.drawCircle(4*s,-34*s,3*s); g.drawCircle(-2*s,-29*s,2*s); g.endFill(); }
      else if (type === 2) { g.beginFill(0x333355); g.drawRect(-4*s, -40*s, 8*s, 40*s); g.endFill(); g.beginFill(0x6666ff, 0.7); g.drawCircle(0, -42*s, 6*s); g.endFill(); g.beginFill(0x9999ff, 0.4); g.drawCircle(0, -42*s, 10*s); g.endFill(); }
      else { g.beginFill(0x555577); g.drawRect(-2*s, -30*s, 4*s, 30*s); g.endFill(); g.beginFill(0x777799); g.drawEllipse(0, -32*s, 14*s, 6*s); g.endFill(); g.beginFill(0x4488ff, 0.5); g.drawCircle(0, -32*s, 3*s); g.endFill(); }
      break;
    case ''dark'':
      if (type === 0) { g.beginFill(0x333344); g.drawRect(-2*s, -30*s, 4*s, 30*s); g.endFill(); g.beginFill(0xccccbb); g.drawCircle(0, -35*s, 8*s); g.endFill(); g.beginFill(0x1a1a2a); g.drawEllipse(-3*s, -36*s, 2.5*s, 3*s); g.drawEllipse(3*s, -36*s, 2.5*s, 3*s); g.endFill(); g.beginFill(0x1a1a2a); g.moveTo(-2*s, -31*s); g.lineTo(0, -29*s); g.lineTo(2*s, -31*s); g.endFill(); }
      else if (type === 1) { g.beginFill(0x333344); g.drawRect(-3*s, -15*s, 6*s, 15*s); g.endFill(); g.beginFill(0x6633aa); g.drawEllipse(0, -18*s, 14*s, 8*s); g.endFill(); g.beginFill(0xaa55ff, 0.4); g.drawEllipse(0, -18*s, 18*s, 10*s); g.endFill(); g.beginFill(0xddaaff, 0.5); g.drawCircle(-4*s, -20*s, 2*s); g.drawCircle(5*s, -17*s, 1.5*s); g.endFill(); }
      else if (type === 2) { g.beginFill(0x444455); g.drawRoundedRect(-10*s, -30*s, 20*s, 30*s, 5*s); g.endFill(); g.beginFill(0x333344); g.drawRect(-1*s, -22*s, 2*s, 10*s); g.drawRect(-5*s, -18*s, 10*s, 2*s); g.endFill(); }
      else { g.beginFill(0x444455); g.drawRect(-2*s, -25*s, 4*s, 25*s); g.endFill(); g.beginFill(0x555566); g.drawRect(-6*s, -30*s, 12*s, 8*s); g.endFill(); g.beginFill(0x00ff88, 0.4); g.drawCircle(0, -26*s, 4*s); g.endFill(); g.beginFill(0x00ff88, 0.15); g.drawCircle(0, -26*s, 10*s); g.endFill(); }
      break;
    case ''ocean'':
      if (type === 0) { g.beginFill(0xff6688); g.moveTo(0,0); g.quadraticCurveTo(10*s,-20*s,5*s,-30*s); g.quadraticCurveTo(2*s,-20*s,0,0); g.endFill(); g.beginFill(0xff88aa); g.moveTo(0,0); g.quadraticCurveTo(-8*s,-18*s,-4*s,-25*s); g.quadraticCurveTo(-1*s,-15*s,0,0); g.endFill(); g.beginFill(0xffaacc); g.drawCircle(4*s,-29*s,3*s); g.drawCircle(-3*s,-24*s,2.5*s); g.endFill(); }
      else if (type === 1) { g.beginFill(0x228855, 0.8); for (var sw2 = 0; sw2 < 3; sw2++) { var sx = (sw2-1)*6*s; g.moveTo(sx,0); g.quadraticCurveTo(sx+8*s,-15*s,sx+2*s,-30*s-sw2*5*s); g.quadraticCurveTo(sx-2*s,-15*s,sx,0); } g.endFill(); }
      else if (type === 2) { g.beginFill(0xffcc88); g.drawEllipse(0, -5*s, 12*s, 8*s); g.endFill(); g.beginFill(0xffddaa); g.drawEllipse(0, -7*s, 8*s, 5*s); g.endFill(); g.lineStyle(1, 0xddaa77); for (var sl = 0; sl < 5; sl++) { g.moveTo(0, -5*s); g.lineTo((sl*5-10)*s, 3*s); } g.lineStyle(0); }
      else { g.beginFill(0x556677); g.drawRect(-2*s, -30*s, 4*s, 30*s); g.endFill(); g.beginFill(0x556677); g.drawRect(-12*s, -8*s, 24*s, 4*s); g.endFill(); g.beginFill(0x667788); g.drawCircle(0, -32*s, 5*s); g.endFill(); g.beginFill(0x445566); g.drawCircle(0, -32*s, 3*s); g.endFill(); }
      break;
    case ''sunset'':
      if (type === 0) { g.beginFill(0x447733); g.drawRect(-2*s, -35*s, 4*s, 35*s); g.endFill(); for (var pet = 0; pet < 8; pet++) { var pa = pet*Math.PI/4; g.beginFill(0xffcc00); g.drawEllipse(Math.cos(pa)*8*s, -40*s+Math.sin(pa)*8*s, 5*s, 3*s); g.endFill(); } g.beginFill(0x885500); g.drawCircle(0, -40*s, 5*s); g.endFill(); }
      else if (type === 1) { g.beginFill(0x558833, 0.7); for (var tg = 0; tg < 5; tg++) { var tx2 = (tg-2)*5*s; g.moveTo(tx2,0); g.quadraticCurveTo(tx2+4*s,-15*s,tx2+2*s,-25*s-_rng()*10*s); g.lineTo(tx2-1*s,-25*s-_rng()*10*s); g.quadraticCurveTo(tx2-4*s,-15*s,tx2,0); } g.endFill(); }
      else if (type === 2) { g.beginFill(0x447733); g.drawRect(-2*s, -20*s, 4*s, 20*s); g.endFill(); var flColors = [0xff6688, 0xffaa44, 0xff88cc, 0xffcc66]; for (var fl = 0; fl < 6; fl++) { g.beginFill(flColors[fl % flColors.length], 0.8); g.drawCircle(_rngRange(-8,8)*s, (-22-_rng()*10)*s, (3+_rng()*2)*s); g.endFill(); } }
      else { g.beginFill(0x558844); g.drawRect(-1.5*s, -40*s, 3*s, 40*s); g.endFill(); g.beginFill(0x885533); g.drawEllipse(0, -42*s, 3.5*s, 8*s); g.endFill(); }
      break;
    default:
      if (type === 0) { g.beginFill(0x886644); g.drawRect(-3*s, -12*s, 6*s, 12*s); g.endFill(); g.beginFill(0xcc3333); g.drawEllipse(0, -15*s, 12*s, 8*s); g.endFill(); g.beginFill(0xffffff, 0.7); g.drawCircle(-4*s, -17*s, 2*s); g.drawCircle(3*s, -14*s, 1.5*s); g.drawCircle(6*s, -16*s, 1*s); g.endFill(); }
      else if (type === 1) { g.beginFill(0x447733); g.drawRect(-1*s, -15*s, 2*s, 15*s); g.endFill(); g.beginFill(0xff6688); g.drawCircle(0, -17*s, 5*s); g.endFill(); g.beginFill(0xffdd44); g.drawCircle(0, -17*s, 2*s); g.endFill(); g.beginFill(0x447733); g.drawRect(3*s, -10*s, 2*s, 10*s); g.endFill(); g.beginFill(0xffaa44); g.drawCircle(4*s, -12*s, 4*s); g.endFill(); }
      else if (type === 2) { g.beginFill(0x338833, 0.8); for (var fn = 0; fn < 4; fn++) { var fa = (fn-1.5)*0.5; g.moveTo(0,0); g.quadraticCurveTo(Math.sin(fa)*20*s,-15*s,Math.sin(fa)*15*s,-25*s); g.lineTo(Math.sin(fa)*12*s,-23*s); g.quadraticCurveTo(Math.sin(fa)*15*s,-12*s,0,0); } g.endFill(); }
      else { g.beginFill(0x5a3a1a); g.drawEllipse(0, -5*s, 20*s, 7*s); g.endFill(); g.beginFill(0x7a5a3a); g.drawCircle(-18*s, -5*s, 7*s); g.endFill(); g.beginFill(0x4a2a0a); g.drawCircle(-18*s, -5*s, 4*s); g.endFill(); }
      break;
  }
  return g;
}

function _drawGroundDetail(x: number, groundY: number): any {
  var g = new PIXI.Graphics();
  g.x = x; g.y = groundY;
  var ds = 2.5;
  switch (THEME) {
    case ''volcanic'': g.lineStyle(3, 0xff4400, 0.7); g.moveTo(-20*ds, 4); g.lineTo(0, -6); g.lineTo(20*ds, 2); g.lineTo(28*ds, 8); g.lineStyle(2, 0xff6600, 0.4); g.moveTo(-12*ds, 8); g.lineTo(6*ds, -2); g.lineTo(22*ds, 10); g.beginFill(0xff3300, 0.2); g.drawEllipse(0, 2, 16*ds, 4); g.endFill(); break;
    case ''arctic'': g.beginFill(0xddeeff, 0.7); g.drawEllipse(0, 0, 35, 10); g.endFill(); g.beginFill(0xeef4ff, 0.5); g.drawEllipse(5, -3, 22, 6); g.endFill(); break;
    case ''candy'': var sc = [0xff6699, 0x66ccff, 0xffcc33, 0x66ff99, 0xff66ff]; for (var j = 0; j < 8; j++) { g.beginFill(sc[j%sc.length]); g.drawRoundedRect(_rngRange(-20,20), _rngRange(-4,4), 8, 3, 1); g.endFill(); } break;
    case ''space'': g.lineStyle(2, 0x4488ff, 0.6); g.moveTo(-15, 4); g.lineTo(0, -4); g.lineTo(18, 6); g.beginFill(0x4488ff, 0.2); g.drawCircle(0, 0, 16); g.endFill(); g.beginFill(0x88aaff, 0.1); g.drawCircle(0, 0, 25); g.endFill(); break;
    case ''dark'': g.beginFill(0x6633aa, 0.15); g.drawEllipse(0, -5, 40, 14); g.endFill(); g.beginFill(0x8844cc, 0.08); g.drawEllipse(0, -8, 55, 18); g.endFill(); break;
    case ''ocean'': g.beginFill(0x66aadd, 0.35); g.drawCircle(-6, -8, 6); g.drawCircle(8, -14, 4.5); g.drawCircle(0, -22, 3); g.drawCircle(-10, -18, 2.5); g.endFill(); break;
    default: g.beginFill(0x55aa33, 0.6); g.moveTo(-10, 0); g.lineTo(-6, -16); g.lineTo(-2, 0); g.moveTo(4, 0); g.lineTo(8, -12); g.lineTo(12, 0); g.moveTo(-3, 0); g.lineTo(1, -10); g.lineTo(5, 0); g.endFill(); break;
  }
  return g;
}

// ======================== FEATURE BANK INTEGRATION ========================
__FEATURE_FACTORIES__

// ======================== GAME SCENE ========================
export class GameScene2D implements GameScene {
  name = ''game'';
  container: any;
  private physics!: PhysicsWorld;
  private playerGfx: any;
  private playerBody: any;
  private playerCtrl!: CharacterController;
  private score = 0;
  private lives = CONFIG.lives;
  private coins: { gfx: any; body: any; baseY: number }[] = [];
  private enemies: { gfx: any; body: any; startX: number; range: number; dir: number }[] = [];
  private clouds: { gfx: any; speed: number }[] = [];
  private bgLayers: { gfx: any; factor: number }[] = [];
  private stars: any;
  private decorTrees: any[] = [];
  private fogLayers: any[] = [];
  private treeSway: any[] = [];
  private waterSurface: any = null;
  private lavaSurface: any = null;
  private invincibleTimer = 0;
  private shakeTimer = 0;
  private shakeIntensity = 0;
  private lastPlayerFacing = 1;
  private _lastAnim = '''';

  constructor() {
    this.container = new PIXI.Container();
  }

  async enter(engine: Engine2D): Promise<void> {
    this.physics = new PhysicsWorld(CONFIG.gravity);
    this.score = 0;
    this.lives = CONFIG.lives;
    this.coins = [];
    this.enemies = [];
    this.clouds = [];
    this.bgLayers = [];
    this.decorTrees = [];
    this.fogLayers = [];
    this.treeSway = [];
    this.invincibleTimer = 0;
    this.shakeTimer = 0;

    await _loadSpriteLib(THEME);
    setNoiseSeed(_seed);

    var W = engine.config.width;
    var H = engine.config.height;
    var WW = CONFIG.worldWidth;
    var WH = CONFIG.worldHeight;

    // ---- Feature Bank: init features ----
__FEATURE_REGISTRATIONS__
    try { engine.features.initAll(); } catch(e) {}

    // ---- 1. GRADIENT SKY ----
    var sky = drawSkyGradient(WW, WH, PAL.skyTop, PAL.skyBottom);
    this.container.addChild(sky);

    // ---- 2. STARS ----
    this.stars = drawStars(WW, WH * 0.5, 80);
    this.container.addChild(this.stars);

    // ---- 3. PARALLAX MOUNTAINS (3 layers) ----
    for (var mi = 0; mi < 3; mi++) {
      var mColor = PAL.mountains[mi] || PAL.mountains[0];
      var mBaseY = CONFIG.groundY - 30 - mi * 60;
      var mMinH = 60 + mi * 30;
      var mMaxH = 120 + mi * 50;
      var mSpacing = 250 - mi * 30;
      var mAlpha = 0.4 + mi * 0.2;
      var mGfx = drawMountainRange(WW, mBaseY, mColor, mAlpha, mMinH, mMaxH, mSpacing, THEME, mi);
      this.container.addChild(mGfx);
      this.bgLayers.push({ gfx: mGfx, factor: 0.1 + mi * 0.15 });
    }

    // ---- 3b. ATMOSPHERIC FOG LAYERS ----
    try {
      this.fogLayers = drawAtmosphericFog(WW, CONFIG.groundY, THEME);
      for (var fi2 = 0; fi2 < this.fogLayers.length; fi2++) {
        this.container.addChild(this.fogLayers[fi2]);
        this.bgLayers.push({ gfx: this.fogLayers[fi2], factor: 0.05 + fi2 * 0.08 });
      }
    } catch(e) {}

    // ---- 4. CLOUDS ----
    if (THEME !== ''space'' && THEME !== ''dark'') {
      var cloudCount = _rngInt(5, 10);
      for (var ci = 0; ci < cloudCount; ci++) {
        var cw = _rngRange(80, 200);
        var ch = _rngRange(25, 45);
        var cloud = drawCloud(cw, ch);
        cloud.x = _rngRange(0, WW);
        cloud.y = _rngRange(50, CONFIG.groundY * 0.4);
        if (THEME === ''volcanic'') { cloud.tint = 0x997766; cloud.alpha = 0.5; }
        this.container.addChild(cloud);
        this.clouds.push({ gfx: cloud, speed: _rngRange(5, 15) });
      }
    }

    // ---- 5. THEME-SPECIFIC DECORATIONS ----
    var decData = _generateDecorations();
    for (var di = 0; di < decData.length; di++) {
      var dd = decData[di];
      var dec = _drawDecoration(dd.type, dd.size);
      dec.x = dd.x;
      dec.y = CONFIG.groundY;
      if (dd.flip) dec.scale.x = -1;
      this.container.addChild(dec);
      this.decorTrees.push(dec);
    }

    // ---- 6. GROUND ----
    var floorH = WH - CONFIG.groundY;
    var ground = drawGroundStrip(WW, CONFIG.groundY, floorH, PAL.ground, PAL.groundTop, THEME);
    this.container.addChild(ground);
    var groundBody = createStaticBody(WW / 2, CONFIG.groundY + 4, WW, 8);
    this.physics.addBody(groundBody);

    // ---- 6b. L-SYSTEM TREES ----
    var treePresetList = TREE_PRESETS[THEME] || [];
    if (treePresetList.length > 0) {
      var treeCount = _rngInt(4, 8);
      var treeSpacing = CONFIG.worldWidth / treeCount;
      for (var ti = 0; ti < treeCount; ti++) {
        var treePreset = treePresetList[_rngInt(0, treePresetList.length - 1)];
        var treeX = ti * treeSpacing + _rngRange(50, treeSpacing - 50);
        var treeSeed = _seed + ti * 137;
        var tree = drawLSystemTree(treeX, CONFIG.groundY, treePreset, THEME, treeSeed);
        this.container.addChild(tree);
        this.treeSway.push(tree);
      }
    }

    // ---- 6c. GROUND DETAILS ----
    var groundDetailCount = _rngInt(12, 24);
    var gdSpacing = CONFIG.worldWidth / groundDetailCount;
    for (var gdi = 0; gdi < groundDetailCount; gdi++) {
      var gdx = gdi * gdSpacing + _rngRange(10, gdSpacing - 10);
      var gd = _drawGroundDetail(gdx, CONFIG.groundY);
      this.container.addChild(gd);
    }

    // ---- 7. PLATFORMS ----
    var platforms = _generatePlatforms();
    for (var pi = 0; pi < platforms.length; pi++) {
      var p = platforms[pi];
      var platGfx = drawPlatformBlock(p.w, 24, PAL.platform, PAL.platformTop, THEME);
      platGfx.x = p.x;
      platGfx.y = p.y;
      this.container.addChild(platGfx);
      var platBody = createOneWayPlatform(p.x, p.y, p.w, 24);
      this.physics.addBody(platBody);
    }

    // ---- 8. PLAYER ----
    this.playerGfx = drawPlayerCharacter(CONFIG.playerSize, PAL.player, PAL.playerLight);
    this.playerGfx.x = CONFIG.playerStartX;
    this.playerGfx.y = CONFIG.groundY - 30;
    this.container.addChild(this.playerGfx);

    this.playerBody = createBody(CONFIG.playerStartX, CONFIG.groundY - 30, 28, 44);
    this.playerBody.sprite = this.playerGfx;
    this.playerBody.tag = ''player'';
    this.physics.addBody(this.playerBody);
    this.playerCtrl = new CharacterController(this.playerBody, {
      moveSpeed: CONFIG.moveSpeed,
      jumpForce: CONFIG.jumpForce,
      doubleJump: CONFIG.doubleJump,
      wallSlide: CONFIG.wallSlide,
    });

    // ---- 9. COINS ----
    var coinData = _generateCoins(platforms);
    for (var coi = 0; coi < coinData.length; coi++) {
      var cp = coinData[coi];
      var coinGfx = drawCoinToken(CONFIG.coinRadius, PAL.coin, PAL.coinGlow);
      coinGfx.x = cp.x;
      coinGfx.y = cp.y;
      this.container.addChild(coinGfx);
      var coinBody = createBody(cp.x, cp.y, 18, 18, { isStatic: true, isSensor: true, tag: ''coin'' });
      coinBody.sprite = coinGfx;
      this.physics.addBody(coinBody);
      this.coins.push({ gfx: coinGfx, body: coinBody, baseY: cp.y });
    }

    // ---- 10. ENEMIES ----
    var enemyData = _generateEnemies();
    for (var ei = 0; ei < enemyData.length; ei++) {
      var ed = enemyData[ei];
      var enemyGfx = drawEnemySlime(CONFIG.enemySize, PAL.enemy, PAL.enemyLight);
      enemyGfx.x = ed.x;
      enemyGfx.y = CONFIG.groundY - 18;
      this.container.addChild(enemyGfx);
      var enemyBody = createBody(ed.x, CONFIG.groundY - 18, 32, 28, { isStatic: true, isSensor: true, tag: ''enemy'' });
      enemyBody.sprite = enemyGfx;
      this.physics.addBody(enemyBody);
      this.enemies.push({ gfx: enemyGfx, body: enemyBody, startX: ed.x, range: ed.range, dir: 1 });
    }

    // ---- 11. COLLISION HANDLER (emits events for Feature Bank) ----
    var self = this;
    this.physics.onSensorOverlap(function(a: any, b: any) {
      var coin = a.tag === ''coin'' ? a : b.tag === ''coin'' ? b : null;
      var enemy = a.tag === ''enemy'' ? a : b.tag === ''enemy'' ? b : null;
      var player = a.tag === ''player'' ? a : b.tag === ''player'' ? b : null;
      if (coin && player && coin.enabled !== false) {
        onCollectSparkle(engine.proton, coin.x, coin.y);
        if (coin.sprite) coin.sprite.visible = false;
        coin.enabled = false;
        self.score += 10;
        try { engine.events.emit(''coin-collect'', { score: self.score, x: coin.x, y: coin.y }); } catch(e) {}
      }
      if (enemy && player && enemy.enabled !== false && self.invincibleTimer <= 0) {
        self.lives--;
        self.invincibleTimer = 1.5;
        engine.juice.shake(engine.world, 10, 0.3);
        engine.juice.hitPause(engine.app, 80);
        engine.juice.flash(self.playerGfx, 0xff0000, 0.15);
        onDeathExplosion(engine.proton, enemy.x, enemy.y, ''#ff4444'');
        self.playerBody.vy = -350;
        try { engine.events.emit(''player-hit'', { lives: self.lives, x: enemy.x, y: enemy.y }); } catch(e) {}
        if (self.lives <= 0) {
          try { engine.events.emit(''player-death'', { score: self.score }); } catch(e) {}
          engine.scene.switch(''gameover'', { score: self.score });
        }
      }
    });

    // ---- 12. AMBIENT PARTICLES ----
    try {
      if (PAL.weather === ''snow'') {
        var snowFx = createSnowEffect(W, H, 0.5);
        if (snowFx && snowFx.emitter) engine.addEmitter(snowFx.emitter);
        for (var spi = 0; spi < platforms.length; spi++) {
          var sp2 = platforms[spi];
          for (var sd = 0; sd < sp2.w / 8; sd++) {
            var snowDot = new PIXI.Graphics();
            snowDot.circle(0, 0, 1 + Math.random() * 1.5);
            snowDot.fill({ color: 0xeef4ff, alpha: 0.6 + Math.random() * 0.3 });
            snowDot.x = sp2.x - sp2.w / 2 + sd * 8 + Math.random() * 6;
            snowDot.y = sp2.y - 2 - Math.random() * 3;
            this.container.addChild(snowDot);
          }
        }
      } else if (PAL.weather === ''rain'') {
        var rainFx = createRainEffect(W, H, 0.5);
        if (rainFx && rainFx.emitter) engine.addEmitter(rainFx.emitter);
      }
      if (PAL.ambient) {
        var ambientFx = createAmbientEffect(PAL.ambient as any, W, H);
        if (ambientFx && ambientFx.emitter) engine.addEmitter(ambientFx.emitter);
      }
      if (THEME === ''forest'' || THEME === ''dark'') {
        var fireflyCount = _rngInt(6, 14);
        for (var ffi = 0; ffi < fireflyCount; ffi++) {
          var ffGlow = new PIXI.Graphics();
          var ffColor = THEME === ''forest'' ? 0xddff44 : 0xaa55ff;
          ffGlow.circle(0, 0, 3);
          ffGlow.fill({ color: ffColor, alpha: 0.6 });
          ffGlow.circle(0, 0, 8);
          ffGlow.fill({ color: ffColor, alpha: 0.15 });
          ffGlow.x = _rngRange(100, WW - 100);
          ffGlow.y = _rngRange(CONFIG.groundY * 0.3, CONFIG.groundY - 50);
          ffGlow.blendMode = ''add'';
          this.container.addChild(ffGlow);
          this.decorTrees.push(ffGlow);
        }
      }
    } catch(e) {}

    // ---- 13. CONTROLS HINT ----
    var hint = engine.createText(''WASD / Arrows + Space'', { fontSize: 11, fill: 0x666666 });
    hint.anchor.set(0.5, 1);
    hint.x = W / 2;
    hint.y = H - 8;
    engine.ui.addChild(hint);

    // ---- 14. CAMERA ----
    engine.camera.follow(this.playerBody);
    engine.camera.worldWidth = CONFIG.worldWidth;
    engine.camera.worldHeight = CONFIG.worldHeight;
    engine.camera.smoothing = 0.08;

    // ---- 15. JUICE EFFECTS ----
    for (var ji = 0; ji < this.coins.length; ji++) {
      engine.juice.float(this.coins[ji].gfx, 5, 2 + _rng() * 0.5);
    }
    engine.juice.breathe(this.playerGfx, 1.03, 1.2);

    var _PIXI = (window as any).PIXI;
    if (_PIXI.filters && _PIXI.filters.DropShadowFilter && !this.playerGfx.filters) {
      this.playerGfx.filters = [new _PIXI.filters.DropShadowFilter({
        offset: { x: 3, y: 5 }, blur: 5, alpha: 0.5, color: 0x000000,
      })];
    }

    // ---- 15b. DYNAMIC WATER/LAVA SURFACE ----
    try {
      if (THEME === ''ocean'') {
        var waterY2 = CONFIG.groundY - 15;
        var waterH2 = CONFIG.worldHeight - waterY2;
        this.waterSurface = createWaterSurface(WW, waterY2, waterH2, 0x1a5276);
        this.container.addChild(this.waterSurface.container);
      } else if (THEME === ''forest'') {
        var pondX = _rngRange(WW * 0.3, WW * 0.6);
        var pondW = _rngRange(300, 600);
        var pondY = CONFIG.groundY - 5;
        var pondH = CONFIG.worldHeight - pondY;
        this.waterSurface = createWaterSurface(pondW, pondY, pondH, 0x2d6a4f);
        this.waterSurface.container.x = pondX;
        this.container.addChild(this.waterSurface.container);
      } else if (THEME === ''volcanic'') {
        var lavaY2 = CONFIG.groundY - 10;
        var lavaH2 = CONFIG.worldHeight - lavaY2;
        this.lavaSurface = createLavaSurface(WW, lavaY2, lavaH2);
        this.container.addChild(this.lavaSurface.container);
      }
    } catch(e) {}

    // ---- 16. LIGHTING LAYER ----
    try {
      var decorPositions = decData.map(function(d: any) { return { x: d.x, y: CONFIG.groundY }; });
      var lightLayer = createLightingLayer(THEME, WW, CONFIG.groundY, decorPositions);
      this.container.addChild(lightLayer);
    } catch(e) {}

    // ---- 17. VIGNETTE ----
    try {
      var vig = drawVignette(W, H);
      engine.ui.addChild(vig);
    } catch(e) {}

    // === AI ENHANCEMENT ZONE ===
    // This game is fully playable. ENHANCE it based on the Creative Brief:
    // - Add themed decorations (torches, mushrooms, crystals, coral, etc.)
    // - Implement specialMechanic if not already active (dash, gravity-flip, etc.)
    // - Add unique enemy types or a boss fight
    // - Add moving/breakable/disappearing platforms
    // - Add themed particle effects beyond ambient
    // - DO NOT delete or rewrite existing code — ADD to it
__CUSTOM_CODE__
  }

  update(engine: Engine2D, dt: number): void {
    this.physics.update(dt);

    // ---- Player movement ----
    if (this.playerCtrl) {
      var wasOnGround = this.playerCtrl.body.onGround;
      this.playerCtrl.update({
        left: engine.input.left,
        right: engine.input.right,
        jump: engine.input.jump,
      }, dt);

      if (engine.input.left) this.lastPlayerFacing = -1;
      if (engine.input.right) this.lastPlayerFacing = 1;
      this.playerGfx.scale.x = this.lastPlayerFacing;

      // AnimatedSprite animation switching
      if (this.playerGfx.textures && this.playerGfx.play) {
        var _sheet = _sheetCache && _sheetCache[''hero''];
        if (_sheet && _sheet.animations) {
          var _anim = ''idle'';
          if (!this.playerCtrl.body.onGround) {
            _anim = ''jump'';
          } else if (engine.input.left || engine.input.right) {
            _anim = ''walk'';
          }
          if (this._lastAnim !== _anim && _sheet.animations[_anim]) {
            this.playerGfx.textures = _sheet.animations[_anim];
            this.playerGfx.animationSpeed = _anim === ''walk'' ? 0.12 : 0.08;
            this.playerGfx.play();
            this._lastAnim = _anim;
          }
        }
      }

      // Squash & stretch
      if (!this.playerCtrl.body.onGround) {
        var vy = this.playerCtrl.body.vy;
        if (vy < -100) this.playerGfx.scale.y = 1.15;
        else if (vy > 100) this.playerGfx.scale.y = 0.9;
      } else {
        this.playerGfx.scale.y += (1 - this.playerGfx.scale.y) * 0.2;
      }

      // Jump dust
      if (!this.playerCtrl.body.onGround && wasOnGround && this.playerCtrl.body.vy < 0) {
        onJumpDust(engine.proton, this.playerCtrl.body.x, this.playerCtrl.body.y + 22);
      }
      // Land impact
      if (this.playerCtrl.body.onGround && !wasOnGround) {
        onLandImpact(engine.proton, this.playerCtrl.body.x, this.playerCtrl.body.y + 22);
        engine.juice.squash(this.playerGfx, 0.7, 1.15);
      }
    }

    // ---- Invincibility blink ----
    if (this.playerGfx) {
      if (this.invincibleTimer > 0) {
        this.invincibleTimer -= dt;
        this.playerGfx.alpha = Math.sin(this.invincibleTimer * 20) > 0 ? 1 : 0.3;
      } else {
        this.playerGfx.alpha = 1;
      }
    }

    // ---- Animate coins ----
    for (var c = 0; c < this.coins.length; c++) {
      var coin = this.coins[c];
      if (coin.gfx.visible) {
        coin.gfx.y = coin.baseY + Math.sin(engine.elapsed * 3 + coin.body.x * 0.01) * 5;
        coin.gfx.rotation = Math.sin(engine.elapsed * 2 + coin.body.x * 0.02) * 0.15;
        if (coin.gfx.children && coin.gfx.children[0]) {
          coin.gfx.children[0].alpha = 0.5 + 0.5 * Math.sin(engine.elapsed * 4 + coin.body.x * 0.03);
        }
        coin.body.y = coin.gfx.y;
      }
    }

    // ---- Animate enemies ----
    for (var e = 0; e < this.enemies.length; e++) {
      var en = this.enemies[e];
      if (en.body.enabled === false) continue;
      en.gfx.x += en.dir * CONFIG.enemySpeed * dt;
      en.body.x = en.gfx.x;
      if (en.gfx.x > en.startX + en.range) en.dir = -1;
      if (en.gfx.x < en.startX - en.range) en.dir = 1;
      en.gfx.scale.x = en.dir;
      en.gfx.scale.y = 1 + Math.sin(engine.elapsed * 5 + e) * 0.08;
    }

    // ---- Star twinkle ----
    if (this.stars) {
      this.stars.alpha = 0.6 + 0.4 * Math.sin(engine.elapsed * 0.5);
    }

    // ---- Fall death ----
    if (this.playerCtrl && this.playerCtrl.body.y > CONFIG.worldHeight + 100) {
      try { engine.events.emit(''player-death'', { score: this.score }); } catch(e) {}
      engine.scene.switch(''gameover'', { score: this.score });
    }

    // ---- Fog drift ----
    for (var fg = 0; fg < this.fogLayers.length; fg++) {
      this.fogLayers[fg].x += (0.3 + fg * 0.2) * dt;
      if (this.fogLayers[fg].x > CONFIG.worldWidth * 0.1) this.fogLayers[fg].x = 0;
    }

    // ---- Wind system ----
    var _windStr = 0.5 + 0.5 * Math.sin(engine.elapsed * 0.15);
    var _windDir = Math.sin(engine.elapsed * 0.07) > 0 ? 1 : -1;

    // ---- Vegetation sway ----
    for (var sw = 0; sw < this.treeSway.length; sw++) {
      var treeObj = this.treeSway[sw];
      var swayA = Math.sin(engine.elapsed * 1.2 + treeObj.x * 0.008) * 0.018 * (0.5 + _windStr);
      var swayB = Math.sin(engine.elapsed * 2.1 + treeObj.x * 0.015) * 0.008;
      treeObj.skew.x = (swayA + swayB) * _windDir;
    }
    for (var dw = 0; dw < this.decorTrees.length; dw++) {
      var decObj = this.decorTrees[dw];
      decObj.skew.x = Math.sin(engine.elapsed * 1.5 + decObj.x * 0.01) * 0.012 * (0.5 + _windStr) * _windDir;
    }

    // ---- Animate clouds ----
    for (var cl = 0; cl < this.clouds.length; cl++) {
      var cloud2 = this.clouds[cl];
      cloud2.gfx.x += (cloud2.speed * (0.6 + _windStr * 0.8)) * dt;
      if (cloud2.gfx.x > CONFIG.worldWidth + 150) {
        cloud2.gfx.x = -150;
      }
    }

    // ---- Animate water/lava surfaces ----
    if (this.waterSurface) { try { this.waterSurface.update(engine.elapsed); } catch(e) {} }
    if (this.lavaSurface) { try { this.lavaSurface.update(engine.elapsed); } catch(e) {} }

    // ---- Feature Bank: update features ----
    try { engine.features.updateAll(dt); } catch(e) {}

    engine.input.endFrame();
  }

  exit(engine: Engine2D): void {
    try { engine.features.destroyAll(); } catch(e) {}
    engine.juice.killAll();
    this.container.removeChildren();
    engine.ui.removeChildren();
  }
}
',
  true,
  true
);

INSERT INTO feature_bank_snippets (id, name, description, category, type, engine, version, keywords, parameters, dependencies, genres, code, is_built_in, is_verified)
VALUES (
  'runner-base',
  'Runner Base Scene',
  'Auto-scrolling runner with speed ramp, procedural platform spawning, jump-only controls, distance scoring',
  'Scene Templates',
  'scene',
  '2d',
  '1.0.0',
  '["runner","endless-runner","auto-scroll","speed"]'::jsonb,
  '[{"name":"theme","type":"string","default":"forest"},{"name":"seed","type":"number","default":1234},{"name":"gravity","type":"number","default":1400},{"name":"jumpForce","type":"number","default":620},{"name":"startSpeed","type":"number","default":220},{"name":"maxSpeed","type":"number","default":550},{"name":"lives","type":"number","default":1}]'::jsonb,
  '[]'::jsonb,
  '["runner"]'::jsonb,
  '// Auto-composed base scene template: runner
import { Engine2D, GameScene, createGame2D, JuiceSystem } from "../engine/core";
import { createBody, createStaticBody, PhysicsWorld, CharacterController } from "../engine/physics";
import { createAmbientEffect, createSnowEffect, createRainEffect, onJumpDust, onLandImpact, onDeathExplosion, onCollectSparkle } from "../engine/effects";
import { PALETTES, lerpColor, setNoiseSeed, drawSkyGradient, drawStars, drawMountainRange, drawCloud, drawGroundStrip, drawPlatformBlock, drawPlayerCharacter, drawCoinToken, drawEnemySlime, drawHeart, drawVignette, drawAtmosphericFog, drawLSystemTree, TREE_PRESETS, drawPointLight, createLightingLayer } from "../config/assets";
import { _loadSpriteLib, _sheetCache } from "../utils/media-stock";

const PIXI = (window as any).PIXI;

// ======================== SEEDED PRNG (Mulberry32) ========================
var _seed = __SEED__;
function _rng() { _seed |= 0; _seed = _seed + 0x6D2B79F5 | 0; var t = Math.imul(_seed ^ _seed >>> 15, 1 | _seed); t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t; return ((t ^ t >>> 14) >>> 0) / 4294967296; }
function _rngRange(min: number, max: number) { return min + _rng() * (max - min); }
function _rngInt(min: number, max: number) { return Math.floor(_rngRange(min, max + 1)); }

// ======================== CONFIGURATION ========================
var THEME = ''__THEME__'';
var PAL = PALETTES[THEME] || PALETTES.forest;
var CONFIG = {
  gravity: __GRAVITY__,
  jumpForce: __JUMP_FORCE__,
  groundY: 600,
  playerX: 150,
  playerSize: 44,
  startSpeed: __START_SPEED__,
  maxSpeed: __MAX_SPEED__,
  speedRamp: 0.4,
  gapChance: 0.25,
  coinChance: 0.6,
  platformMinW: 120,
  platformMaxW: 280,
  lives: __LIVES__,
};

// ======================== FEATURE BANK INTEGRATION ========================
__FEATURE_FACTORIES__

// ======================== GAME SCENE ========================
export class GameScene2D implements GameScene {
  name = ''game'';
  container: any;
  private physics!: PhysicsWorld;
  private playerGfx: any; private playerBody: any; private playerCtrl!: CharacterController;
  private score = 0; private distance = 0; private speed = CONFIG.startSpeed;
  private platforms: { gfx: any; body: any; w: number }[] = [];
  private coins: { gfx: any; body: any }[] = [];
  private obstacles: { gfx: any; body: any }[] = [];
  private bgLayers: { gfx: any; factor: number }[] = [];
  private treeSway: any[] = [];
  private gameOver = false;

  constructor() { this.container = new PIXI.Container(); }

  async enter(engine: Engine2D): Promise<void> {
    this.physics = new PhysicsWorld(CONFIG.gravity);
    this.speed = CONFIG.startSpeed; this.score = 0; this.distance = 0; this.gameOver = false;
    this.platforms = []; this.coins = []; this.obstacles = []; this.bgLayers = []; this.treeSway = [];
    await _loadSpriteLib(THEME);
    setNoiseSeed(_seed);
    var W = engine.config.width, H = engine.config.height, WW = W * 4;

    // ---- Feature Bank: init features ----
__FEATURE_REGISTRATIONS__
    try { engine.features.initAll(); } catch(e) {}

    // ---- VISUAL ATMOSPHERE ----
    this.container.addChild(drawSkyGradient(WW, H, PAL.skyTop, PAL.skyBottom));
    this.container.addChild(drawStars(WW, H * 0.4, 50));
    for (var mi = 0; mi < 3; mi++) {
      var mGfx = drawMountainRange(WW, CONFIG.groundY - 20 - mi * 40, PAL.mountains[mi] || PAL.mountains[0], 0.4 + mi * 0.2, 40 + mi * 20, 80 + mi * 35, 220 - mi * 25, THEME, mi);
      this.container.addChild(mGfx); this.bgLayers.push({ gfx: mGfx, factor: 0.1 + mi * 0.12 });
    }
    try { var fl = drawAtmosphericFog(WW, CONFIG.groundY, THEME); for (var f = 0; f < fl.length; f++) this.container.addChild(fl[f]); } catch(e) {}

    // ---- INITIAL GROUND PLATFORMS ----
    var px = 0;
    while (px < WW) {
      var pw = CONFIG.platformMinW + _rng() * (CONFIG.platformMaxW - CONFIG.platformMinW);
      var platGfx = drawPlatformBlock(pw, 30, PAL.ground, PAL.groundTop, THEME);
      platGfx.x = px; platGfx.y = CONFIG.groundY;
      this.container.addChild(platGfx);
      var platBody = createStaticBody(px + pw / 2, CONFIG.groundY + 4, pw, 8);
      this.physics.addBody(platBody);
      this.platforms.push({ gfx: platGfx, body: platBody, w: pw });
      if (_rng() < CONFIG.coinChance) {
        var coinGfx = drawCoinToken(8, PAL.coin, PAL.coinGlow);
        coinGfx.x = px + pw / 2; coinGfx.y = CONFIG.groundY - 50;
        this.container.addChild(coinGfx);
        var coinBody = createBody(coinGfx.x, coinGfx.y, 14, 14, { isStatic: true, isSensor: true, tag: ''coin'' });
        coinBody.sprite = coinGfx; this.physics.addBody(coinBody);
        this.coins.push({ gfx: coinGfx, body: coinBody });
      }
      px += pw + (_rng() < CONFIG.gapChance ? 60 + _rng() * 80 : 0);
    }

    // ---- TREES ----
    var tp = TREE_PRESETS[THEME] || [];
    if (tp.length > 0) { for (var ti = 0; ti < 5; ti++) {
      var tree = drawLSystemTree(ti * (WW / 5) + _rngRange(0, 150), CONFIG.groundY, tp[ti % tp.length], THEME, _seed + ti);
      this.container.addChild(tree); this.treeSway.push(tree);
    }}

    // ---- LIGHTING ----
    try { this.container.addChild(createLightingLayer(THEME, WW, CONFIG.groundY, [])); } catch(e) {}

    // ---- PLAYER ----
    this.playerGfx = drawPlayerCharacter(CONFIG.playerSize, PAL.player, PAL.playerLight);
    this.playerGfx.x = CONFIG.playerX; this.playerGfx.y = CONFIG.groundY - 30;
    this.container.addChild(this.playerGfx);
    this.playerBody = createBody(CONFIG.playerX, CONFIG.groundY - 30, 26, 40);
    this.playerBody.sprite = this.playerGfx; this.playerBody.tag = ''player'';
    this.physics.addBody(this.playerBody);
    this.playerCtrl = new CharacterController(this.playerBody, { moveSpeed: 0, jumpForce: CONFIG.jumpForce, doubleJump: true, wallSlide: false });

    // ---- COLLISION ----
    var self = this;
    this.physics.onSensorOverlap(function(a: any, b: any) {
      var coin = a.tag === ''coin'' ? a : b.tag === ''coin'' ? b : null;
      if (coin && coin.enabled !== false) {
        onCollectSparkle(engine.proton, coin.x, coin.y);
        coin.sprite.visible = false; coin.enabled = false; self.score += 10;
        try { engine.events.emit(''coin-collect'', { score: self.score, x: coin.x, y: coin.y }); } catch(e) {}
      }
    });

    // ---- CONTROLS HINT ----
    var hint = engine.createText(''Space / Up to Jump'', { fontSize: 11, fill: 0x666666 });
    hint.anchor.set(0.5, 1); hint.x = W / 2; hint.y = H - 8; engine.ui.addChild(hint);

    // ---- VIGNETTE ----
    try { engine.ui.addChild(drawVignette(W, H)); } catch(e) {}

    // ---- CAMERA ----
    engine.camera.follow(this.playerBody); engine.camera.worldWidth = WW; engine.camera.worldHeight = H; engine.camera.smoothing = 0.06;
    engine.juice.breathe(this.playerGfx, 1.03, 1.5);
    try { if (PAL.ambient) { var af = createAmbientEffect(PAL.ambient as any, W, H); if (af && af.emitter) engine.addEmitter(af.emitter); } } catch(e) {}

    // === AI ENHANCEMENT ZONE ===
__CUSTOM_CODE__
  }

  update(engine: Engine2D, dt: number): void {
    if (this.gameOver || !this.playerGfx) { engine.input.endFrame(); return; }
    this.physics.update(dt);

    // Auto-run
    if (this.playerBody) {
      this.playerBody.vx = this.speed;
      this.playerGfx.x = this.playerBody.x; this.playerGfx.y = this.playerBody.y;
    }
    // Jump
    if (this.playerCtrl) { this.playerCtrl.update({ left: false, right: false, jump: engine.input.jump }, dt); }
    // Speed ramp
    this.speed = Math.min(CONFIG.maxSpeed, this.speed + CONFIG.speedRamp * dt);
    this.distance += this.speed * dt * 0.01;
    try { engine.events.emit(''distance-update'', { distance: Math.floor(this.distance), score: this.score + Math.floor(this.distance) }); } catch(e) {}

    // Coin bob
    for (var c = 0; c < this.coins.length; c++) {
      if (this.coins[c].gfx.visible) this.coins[c].gfx.y += Math.sin(engine.elapsed * 3 + c) * 0.3;
    }
    // Tree sway
    for (var sw = 0; sw < this.treeSway.length; sw++) {
      this.treeSway[sw].skew.x = Math.sin(engine.elapsed * 1.2 + this.treeSway[sw].x * 0.008) * 0.015;
    }
    // Fall death
    if (this.playerBody && this.playerBody.y > CONFIG.groundY + 200) {
      this.gameOver = true;
      var finalScore = this.score + Math.floor(this.distance);
      try { engine.events.emit(''player-death'', { score: finalScore }); } catch(e) {}
      engine.scene.switch(''gameover'', { score: finalScore });
    }

    // ---- Feature Bank: update features ----
    try { engine.features.updateAll(dt); } catch(e) {}

    engine.input.endFrame();
  }

  exit(engine: Engine2D): void {
    try { engine.features.destroyAll(); } catch(e) {}
    engine.juice.killAll(); this.container.removeChildren(); engine.ui.removeChildren();
  }
}
',
  true,
  true
);

INSERT INTO feature_bank_snippets (id, name, description, category, type, engine, version, keywords, parameters, dependencies, genres, code, is_built_in, is_verified)
VALUES (
  'puzzle-base',
  'Puzzle Base Scene (Match-3)',
  'Grid-based match-3 gem game with pointer input, swap animation, match detection, gravity cascade, new gem spawning',
  'Scene Templates',
  'scene',
  '2d',
  '1.0.0',
  '["puzzle","match-3","gems","grid","cascade"]'::jsonb,
  '[{"name":"theme","type":"string","default":"candy"},{"name":"seed","type":"number","default":1234},{"name":"gridCols","type":"number","default":7},{"name":"gridRows","type":"number","default":7},{"name":"gemColorCount","type":"number","default":6}]'::jsonb,
  '[]'::jsonb,
  '["puzzle"]'::jsonb,
  '// Auto-composed base scene template: puzzle (match-3)
import { Engine2D, GameScene, createGame2D, JuiceSystem } from "../engine/core";
import { onCollectSparkle, createAmbientEffect } from "../engine/effects";
import { PALETTES, lerpColor, setNoiseSeed, drawSkyGradient, drawStars, drawHeart, drawGemShape, drawVignette, drawAtmosphericFog, drawPointLight, createLightingLayer } from "../config/assets";
import { _loadSpriteLib, _sheetCache } from "../utils/media-stock";

const PIXI = (window as any).PIXI;

// ======================== SEEDED PRNG (Mulberry32) ========================
var _seed = __SEED__;
function _rng() { _seed |= 0; _seed = _seed + 0x6D2B79F5 | 0; var t = Math.imul(_seed ^ _seed >>> 15, 1 | _seed); t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t; return ((t ^ t >>> 14) >>> 0) / 4294967296; }
function _rngRange(min: number, max: number) { return min + _rng() * (max - min); }
function _rngInt(min: number, max: number) { return Math.floor(_rngRange(min, max + 1)); }

// ======================== CONFIGURATION ========================
var THEME = ''__THEME__'';
var PAL = PALETTES[THEME] || PALETTES.candy;
var CONFIG = {
  cols: __GRID_COLS__,
  rows: __GRID_ROWS__,
  cellSize: __GRID_COLS__ > 7 ? 48 : 52,
  padding: 3,
  gemColors: __GEM_COLORS__,
  matchMin: 3,
  fallSpeed: 500,
  swapDur: 0.15,
};

// ======================== FEATURE BANK INTEGRATION ========================
__FEATURE_FACTORIES__

// ======================== GAME SCENE ========================
export class GameScene2D implements GameScene {
  name = ''game'';
  container: any;
  private board: any;
  private grid: { color: number; gfx: any; row: number; col: number }[][] = [];
  private score = 0;
  private selected: { r: number; c: number } | null = null;
  private animating = false;
  private boardX = 0; private boardY = 0;

  constructor() { this.container = new PIXI.Container(); }

  async enter(engine: Engine2D): Promise<void> {
    this.score = 0; this.selected = null; this.animating = false; this.grid = [];
    await _loadSpriteLib(THEME);
    setNoiseSeed(_seed);
    var W = engine.config.width, H = engine.config.height;

    // ---- Feature Bank: init features ----
__FEATURE_REGISTRATIONS__
    try { engine.features.initAll(); } catch(e) {}

    // ---- VISUAL ATMOSPHERE ----
    this.container.addChild(drawSkyGradient(W, H, PAL.skyTop, PAL.skyBottom));
    this.container.addChild(drawStars(W, H * 0.35, 35));
    try { var fl = drawAtmosphericFog(W, H * 0.85, THEME); for (var f = 0; f < fl.length; f++) this.container.addChild(fl[f]); } catch(e) {}
    try { this.container.addChild(createLightingLayer(THEME, W, H * 0.85, [])); } catch(e) {}
    try { if (PAL.ambient) { var af = createAmbientEffect(PAL.ambient as any, W, H); if (af && af.emitter) engine.addEmitter(af.emitter); } } catch(e) {}

    // ---- BOARD ----
    var bw = CONFIG.cols * (CONFIG.cellSize + CONFIG.padding);
    var bh = CONFIG.rows * (CONFIG.cellSize + CONFIG.padding);
    this.boardX = (W - bw) / 2; this.boardY = (H - bh) / 2 + 30;
    this.board = new PIXI.Container(); this.board.x = this.boardX; this.board.y = this.boardY;
    var bg = new PIXI.Graphics(); bg.roundRect(-10, -10, bw + 20, bh + 20, 12); bg.fill({ color: 0x000000, alpha: 0.3 });
    this.board.addChild(bg);
    this.container.addChild(this.board);

    // Fill grid (no initial matches)
    for (var r = 0; r < CONFIG.rows; r++) {
      this.grid[r] = [];
      for (var c = 0; c < CONFIG.cols; c++) {
        var ci2 = _rngInt(0, CONFIG.gemColors.length - 1);
        while ((c >= 2 && this.grid[r][c-1] && this.grid[r][c-2] && CONFIG.gemColors[ci2] === this.grid[r][c-1].color && CONFIG.gemColors[ci2] === this.grid[r][c-2].color) ||
               (r >= 2 && this.grid[r-1] && this.grid[r-2] && this.grid[r-1][c] && this.grid[r-2][c] && CONFIG.gemColors[ci2] === this.grid[r-1][c].color && CONFIG.gemColors[ci2] === this.grid[r-2][c].color)) {
          ci2 = (ci2 + 1) % CONFIG.gemColors.length;
        }
        var gem = this._createGem(c, r, CONFIG.gemColors[ci2]);
        this.grid[r][c] = gem;
      }
    }

    // ---- INPUT (click to select/swap) ----
    var self = this;
    this.board.eventMode = ''static'';
    this.board.on(''pointerdown'', function(e: any) {
      if (self.animating) return;
      var lp = self.board.toLocal(e.global);
      var col = Math.floor(lp.x / (CONFIG.cellSize + CONFIG.padding));
      var row = Math.floor(lp.y / (CONFIG.cellSize + CONFIG.padding));
      if (col < 0 || col >= CONFIG.cols || row < 0 || row >= CONFIG.rows) return;
      if (!self.selected) { self.selected = { r: row, c: col }; self.grid[row][col].gfx.alpha = 0.6; return; }
      var dr = Math.abs(self.selected.r - row), dc = Math.abs(self.selected.c - col);
      self.grid[self.selected.r][self.selected.c].gfx.alpha = 1;
      if ((dr === 1 && dc === 0) || (dr === 0 && dc === 1)) { self._swap(self.selected.r, self.selected.c, row, col, engine); }
      self.selected = null;
    });

    // ---- CONTROLS HINT ----
    var hint = engine.createText(''Click gems to match 3+'', { fontSize: 11, fill: 0x666666 });
    hint.anchor.set(0.5, 1); hint.x = W / 2; hint.y = H - 8; engine.ui.addChild(hint);

    // ---- VIGNETTE ----
    try { engine.ui.addChild(drawVignette(W, H)); } catch(e) {}

    // === AI ENHANCEMENT ZONE ===
__CUSTOM_CODE__
  }

  private _createGem(col: number, row: number, color: number): any {
    var s = CONFIG.cellSize;
    var g = new PIXI.Graphics();
    g.roundRect(0, 0, s, s, 8); g.fill(color);
    g.roundRect(3, 3, s * 0.4, s * 0.3, 4); g.fill({ color: 0xffffff, alpha: 0.25 });
    g.x = col * (s + CONFIG.padding); g.y = row * (s + CONFIG.padding);
    this.board.addChild(g);
    return { color: color, gfx: g, row: row, col: col };
  }

  private _swap(r1: number, c1: number, r2: number, c2: number, engine: Engine2D): void {
    this.animating = true;
    var a = this.grid[r1][c1], b = this.grid[r2][c2];
    this.grid[r1][c1] = b; this.grid[r2][c2] = a;
    b.row = r1; b.col = c1; a.row = r2; a.col = c2;
    var s = CONFIG.cellSize + CONFIG.padding;
    var self = this;
    var gsap = (window as any).gsap;
    if (gsap) {
      gsap.to(a.gfx, { x: c2 * s, y: r2 * s, duration: CONFIG.swapDur });
      gsap.to(b.gfx, { x: c1 * s, y: r1 * s, duration: CONFIG.swapDur, onComplete: function() { self._checkMatches(engine); } });
    } else { a.gfx.x = c2 * s; a.gfx.y = r2 * s; b.gfx.x = c1 * s; b.gfx.y = r1 * s; self._checkMatches(engine); }
  }

  private _checkMatches(engine: Engine2D): void {
    var matched: boolean[][] = [];
    for (var r = 0; r < CONFIG.rows; r++) { matched[r] = []; for (var c = 0; c < CONFIG.cols; c++) matched[r][c] = false; }
    // Horizontal
    for (var r2 = 0; r2 < CONFIG.rows; r2++) {
      for (var c2 = 0; c2 < CONFIG.cols - 2; c2++) {
        if (this.grid[r2][c2].color === this.grid[r2][c2+1].color && this.grid[r2][c2].color === this.grid[r2][c2+2].color) {
          matched[r2][c2] = matched[r2][c2+1] = matched[r2][c2+2] = true;
        }
      }
    }
    // Vertical
    for (var c3 = 0; c3 < CONFIG.cols; c3++) {
      for (var r3 = 0; r3 < CONFIG.rows - 2; r3++) {
        if (this.grid[r3][c3].color === this.grid[r3+1][c3].color && this.grid[r3][c3].color === this.grid[r3+2][c3].color) {
          matched[r3][c3] = matched[r3+1][c3] = matched[r3+2][c3] = true;
        }
      }
    }
    // Remove matched
    var count = 0;
    for (var r4 = 0; r4 < CONFIG.rows; r4++) {
      for (var c4 = 0; c4 < CONFIG.cols; c4++) {
        if (matched[r4][c4]) {
          count++;
          this.grid[r4][c4].gfx.visible = false;
          try { onCollectSparkle(engine.proton, this.boardX + c4 * (CONFIG.cellSize + CONFIG.padding) + CONFIG.cellSize / 2, this.boardY + r4 * (CONFIG.cellSize + CONFIG.padding) + CONFIG.cellSize / 2); } catch(e) {}
        }
      }
    }
    if (count === 0) { this.animating = false; return; }
    this.score += count * 10;
    try { engine.events.emit(''match-clear'', { count: count, score: this.score }); } catch(e) {}
    var self = this;
    setTimeout(function() { self._cascade(engine); }, 200);
  }

  private _cascade(engine: Engine2D): void {
    var s = CONFIG.cellSize + CONFIG.padding;
    var gsap = (window as any).gsap;
    for (var c = 0; c < CONFIG.cols; c++) {
      var writeRow = CONFIG.rows - 1;
      for (var r = CONFIG.rows - 1; r >= 0; r--) {
        if (this.grid[r][c].gfx.visible) {
          if (r !== writeRow) {
            var gem = this.grid[r][c];
            this.grid[writeRow][c] = gem; gem.row = writeRow; gem.col = c;
            if (gsap) gsap.to(gem.gfx, { y: writeRow * s, duration: 0.15 }); else gem.gfx.y = writeRow * s;
          }
          writeRow--;
        }
      }
      for (var dr = writeRow; dr >= 0; dr--) {
        if (this.grid[dr][c] && this.grid[dr][c].gfx) { this.grid[dr][c].gfx.destroy(); }
      }
      for (var nr = writeRow; nr >= 0; nr--) {
        var ci = _rngInt(0, CONFIG.gemColors.length - 1);
        var newGem = this._createGem(c, nr, CONFIG.gemColors[ci]);
        newGem.gfx.y = -s;
        this.grid[nr][c] = newGem;
        if (gsap) gsap.to(newGem.gfx, { y: nr * s, duration: 0.2, delay: (writeRow - nr) * 0.03 }); else newGem.gfx.y = nr * s;
      }
    }
    var self = this;
    setTimeout(function() { self._checkMatches(engine); }, 300);
  }

  update(engine: Engine2D, dt: number): void {
    try { engine.features.updateAll(dt); } catch(e) {}
    engine.input.endFrame();
  }

  exit(engine: Engine2D): void {
    try { engine.features.destroyAll(); } catch(e) {}
    this.container.removeChildren(); engine.ui.removeChildren();
  }
}
',
  true,
  true
);

INSERT INTO feature_bank_snippets (id, name, description, category, type, engine, version, keywords, parameters, dependencies, genres, code, is_built_in, is_verified)
VALUES (
  'shooter-base',
  'Shooter Base Scene',
  'Space shooter with auto-fire bullets, wave-based enemy spawning, starfield background, collision detection',
  'Scene Templates',
  'scene',
  '2d',
  '1.0.0',
  '["shooter","space","bullets","waves","enemies"]'::jsonb,
  '[{"name":"theme","type":"string","default":"space"},{"name":"seed","type":"number","default":1234},{"name":"moveSpeed","type":"number","default":320},{"name":"fireRate","type":"number","default":0.14},{"name":"enemySpeed","type":"number","default":100},{"name":"enemySpawnRate","type":"number","default":1.4},{"name":"lives","type":"number","default":3}]'::jsonb,
  '[]'::jsonb,
  '["shooter"]'::jsonb,
  '// Auto-composed base scene template: shooter
import { Engine2D, GameScene, createGame2D, JuiceSystem } from "../engine/core";
import { createExplosionEffect, createAmbientEffect, onDeathExplosion, onCollectSparkle } from "../engine/effects";
import { PALETTES, lerpColor, setNoiseSeed, drawSkyGradient, drawStars, drawCoinToken, drawHeart, drawShipShape, drawVignette, drawAtmosphericFog, drawPointLight, createLightingLayer } from "../config/assets";
import { _loadSpriteLib, _sheetCache } from "../utils/media-stock";

const PIXI = (window as any).PIXI;

// ======================== SEEDED PRNG (Mulberry32) ========================
var _seed = __SEED__;
function _rng() { _seed |= 0; _seed = _seed + 0x6D2B79F5 | 0; var t = Math.imul(_seed ^ _seed >>> 15, 1 | _seed); t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t; return ((t ^ t >>> 14) >>> 0) / 4294967296; }
function _rngRange(min: number, max: number) { return min + _rng() * (max - min); }
function _rngInt(min: number, max: number) { return Math.floor(_rngRange(min, max + 1)); }

// ======================== CONFIGURATION ========================
var THEME = ''__THEME__'';
var PAL = PALETTES[THEME] || PALETTES.space;
var CONFIG = {
  playerSpeed: __MOVE_SPEED__,
  bulletSpeed: 650,
  fireRate: __FIRE_RATE__,
  enemyBaseSpeed: __ENEMY_SPEED__,
  enemySpawnRate: __ENEMY_SPAWN_RATE__,
  lives: __LIVES__,
  playerSize: 48,
  enemySize: 44,
  bulletW: 6,
  bulletH: 18,
};

// ======================== FEATURE BANK INTEGRATION ========================
__FEATURE_FACTORIES__

// ======================== GAME SCENE ========================
export class GameScene2D implements GameScene {
  name = ''game'';
  container: any;
  private playerGfx: any;
  private score = 0; private lives = CONFIG.lives; private fireCooldown = 0; private spawnTimer = 0; private wave = 1;
  private bullets: { gfx: any; vy: number }[] = [];
  private enemies: { gfx: any; vx: number; vy: number; hp: number }[] = [];
  private stars: any;

  constructor() { this.container = new PIXI.Container(); }

  async enter(engine: Engine2D): Promise<void> {
    this.score = 0; this.lives = CONFIG.lives; this.fireCooldown = 0; this.spawnTimer = 0; this.wave = 1;
    this.bullets = []; this.enemies = [];
    await _loadSpriteLib(THEME);
    setNoiseSeed(_seed);
    var W = engine.config.width, H = engine.config.height;

    // ---- Feature Bank: init features ----
__FEATURE_REGISTRATIONS__
    try { engine.features.initAll(); } catch(e) {}

    // ---- VISUAL ATMOSPHERE ----
    var skyGfx = new PIXI.Graphics();
    if (PIXI.FillGradient) {
      var sg = new PIXI.FillGradient({ type: ''linear'', start: { x: 0, y: 0 }, end: { x: 0, y: 1 },
        colorStops: [{ offset: 0, color: ''#0a0a2e'' }, { offset: 0.5, color: ''#1a1a4e'' }, { offset: 1, color: ''#2a1a3e'' }] });
      skyGfx.rect(0, 0, W, H); skyGfx.fill(sg);
    } else { skyGfx.rect(0, 0, W, H); skyGfx.fill(0x0a0a2e); }
    this.container.addChild(skyGfx);
    this.stars = drawStars(W, H, 150); this.container.addChild(this.stars);
    try { if (PAL.ambient) { var af = createAmbientEffect(PAL.ambient as any, W, H); if (af && af.emitter) engine.addEmitter(af.emitter); } } catch(e) {}

    // ---- PLAYER SHIP ----
    this.playerGfx = drawShipShape(CONFIG.playerSize, PAL.player, PAL.playerLight);
    this.playerGfx.x = W / 2; this.playerGfx.y = H - 90;
    this.container.addChild(this.playerGfx);

    // ---- CONTROLS HINT ----
    var hint = engine.createText(''Left/Right to move, auto-fire'', { fontSize: 11, fill: 0x666666 });
    hint.anchor.set(0.5, 1); hint.x = W / 2; hint.y = H - 8; engine.ui.addChild(hint);

    // ---- VIGNETTE ----
    try { engine.ui.addChild(drawVignette(W, H)); } catch(e) {}

    // === AI ENHANCEMENT ZONE ===
__CUSTOM_CODE__
  }

  private _spawnEnemy(W: number): void {
    var container = new PIXI.Container();
    var g = new PIXI.Graphics();
    var sz = CONFIG.enemySize;
    var eColor = [0xff4444, 0xff8844, 0xffaa00, 0xcc44ff, 0x44ffaa][_rngInt(0, 4)];
    g.moveTo(0, sz * 0.5); g.lineTo(-sz * 0.45, -sz * 0.2); g.lineTo(-sz * 0.2, -sz * 0.15);
    g.lineTo(0, -sz * 0.5); g.lineTo(sz * 0.2, -sz * 0.15); g.lineTo(sz * 0.45, -sz * 0.2); g.closePath();
    g.fill(eColor);
    g.circle(0, -sz * 0.05, sz * 0.12); g.fill(0xffffff);
    g.circle(0, -sz * 0.05, sz * 0.08); g.fill(eColor);
    g.moveTo(-sz * 0.35, -sz * 0.1); g.lineTo(-sz * 0.2, sz * 0.1); g.lineTo(-sz * 0.15, -sz * 0.05); g.closePath();
    g.fill({ color: 0xffffff, alpha: 0.2 });
    g.moveTo(sz * 0.35, -sz * 0.1); g.lineTo(sz * 0.2, sz * 0.1); g.lineTo(sz * 0.15, -sz * 0.05); g.closePath();
    g.fill({ color: 0xffffff, alpha: 0.2 });
    container.addChild(g);
    if (PIXI.filters && PIXI.filters.GlowFilter) {
      try { container.filters = [new PIXI.filters.GlowFilter({ distance: 8, outerStrength: 1.5, color: eColor })]; } catch(e) {}
    }
    container.x = 40 + _rng() * (W - 80); container.y = -40;
    this.container.addChild(container);
    var vx = (_rng() - 0.5) * 80;
    var vy = CONFIG.enemyBaseSpeed * (0.8 + _rng() * 0.4 + this.wave * 0.08);
    this.enemies.push({ gfx: container, vx: vx, vy: vy, hp: 1 });
  }

  private _fireBullet(): void {
    var g = new PIXI.Graphics();
    var bw = CONFIG.bulletW, bh = CONFIG.bulletH;
    g.roundRect(-bw, -bh - 2, bw * 2, bh + 4, 3);
    g.fill({ color: 0x44ddff, alpha: 0.3 });
    g.roundRect(-bw / 2, -bh, bw, bh, 2);
    g.fill(0x44ddff);
    g.roundRect(-bw / 2 + 1, -bh + 2, bw - 2, bh * 0.5, 1);
    g.fill({ color: 0xffffff, alpha: 0.8 });
    g.blendMode = ''add'';
    g.x = this.playerGfx.x; g.y = this.playerGfx.y - 25;
    this.container.addChild(g);
    this.bullets.push({ gfx: g, vy: -CONFIG.bulletSpeed });
  }

  update(engine: Engine2D, dt: number): void {
    var W = engine.config.width, H = engine.config.height;

    // Player movement
    if (this.playerGfx) {
      if (engine.input.left) this.playerGfx.x -= CONFIG.playerSpeed * dt;
      if (engine.input.right) this.playerGfx.x += CONFIG.playerSpeed * dt;
      this.playerGfx.x = Math.max(30, Math.min(W - 30, this.playerGfx.x));
    }

    // Auto-fire
    if (!this.playerGfx) { engine.input.endFrame(); return; }
    this.fireCooldown -= dt;
    if (this.fireCooldown <= 0) { this._fireBullet(); this.fireCooldown = CONFIG.fireRate; }

    // Move bullets
    for (var bi = this.bullets.length - 1; bi >= 0; bi--) {
      var b = this.bullets[bi];
      b.gfx.y += b.vy * dt;
      if (b.gfx.y < -20) { b.gfx.destroy(); this.bullets.splice(bi, 1); }
    }

    // Spawn enemies
    this.spawnTimer -= dt;
    if (this.spawnTimer <= 0) { this._spawnEnemy(W); this.spawnTimer = CONFIG.enemySpawnRate * Math.max(0.3, 1 - this.wave * 0.05); }

    // Move enemies
    for (var ei = this.enemies.length - 1; ei >= 0; ei--) {
      var en = this.enemies[ei];
      en.gfx.x += en.vx * dt; en.gfx.y += en.vy * dt;
      en.gfx.rotation = Math.sin(engine.elapsed * 3 + ei) * 0.1;
      if (en.gfx.y > H + 40) { en.gfx.destroy(); this.enemies.splice(ei, 1); continue; }
      // Hit player
      if (this.playerGfx && Math.abs(en.gfx.x - this.playerGfx.x) < 28 && Math.abs(en.gfx.y - this.playerGfx.y) < 28) {
        try { onDeathExplosion(engine.proton, en.gfx.x, en.gfx.y, ''#ff4444''); } catch(e) {}
        en.gfx.destroy(); this.enemies.splice(ei, 1);
        this.lives--;
        try { engine.events.emit(''player-hit'', { lives: this.lives, x: en.gfx.x, y: en.gfx.y }); } catch(e) {}
        engine.juice.shake(engine.world, 8, 0.25);
        if (this.lives <= 0) {
          try { engine.events.emit(''player-death'', { score: this.score }); } catch(e) {}
          engine.scene.switch(''gameover'', { score: this.score });
        }
        continue;
      }
      // Bullet-enemy collision
      for (var bj = this.bullets.length - 1; bj >= 0; bj--) {
        var bl = this.bullets[bj];
        if (Math.abs(bl.gfx.x - en.gfx.x) < 20 && Math.abs(bl.gfx.y - en.gfx.y) < 22) {
          try { onCollectSparkle(engine.proton, en.gfx.x, en.gfx.y); } catch(e) {}
          en.gfx.destroy(); this.enemies.splice(ei, 1);
          bl.gfx.destroy(); this.bullets.splice(bj, 1);
          this.score += 100;
          try { engine.events.emit(''enemy-kill'', { score: this.score, x: en.gfx.x, y: en.gfx.y }); } catch(e) {}
          if (this.score > 0 && this.score % 1000 === 0) { this.wave++; }
          break;
        }
      }
    }

    // Star scroll
    if (this.stars) this.stars.y += 15 * dt;

    // ---- Feature Bank: update features ----
    try { engine.features.updateAll(dt); } catch(e) {}

    engine.input.endFrame();
  }

  exit(engine: Engine2D): void {
    try { engine.features.destroyAll(); } catch(e) {}
    this.container.removeChildren(); engine.ui.removeChildren();
  }
}
',
  true,
  true
);


